In [2]:
import os
def createfolder(folder):
    try:
        if not os.path.exists(folder):
            os.makedirs(folder)
    except OSError:
        print('Error: creating directory' + folder)
        

In [3]:
import PIL
from PIL import Image

def load_image_file(file, mode='RGB'):
    im = PIL.Image.open(file)
    if mode:
        im = im.convert(mode)
    return np.array(im)

In [4]:
import cv2
import numpy as np
import face_recognition
import re

dirname = 'deepfake-data_subset1/original_videos/'
videoname = '643049'
video_path = dirname + videoname+'/'
frame_save_path = videoname+'_frame'
#'C:\Users\user\Documents\cyber17\Face_Detection\'
video = cv2.VideoCapture(video_path+videoname+'_D_002.mp4')
count = 0

videoframe = video.get(cv2.CAP_PROP_POS_FRAMES)
videocount = video.get(cv2.CAP_PROP_FRAME_COUNT)

createfolder(frame_save_path)

while video.isOpened():
    #ret 은 프레임이 존재하지 않을때 T/F 반환
    #frame 은 프레임 반환
    if(videoframe == videocount):
        video.open(video_path+videoname+'_D_002.mp4')
    
    #video.set(cv2.CAP_PROP_POS_MSEC, (count*1000))
    ret, frame = video.read()
    #print(frame)
    
    if ret == False:
        print("Frame doesn't Exist")
        break
    
    frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)    
    
    try:
        
        #face_location 은 얼굴 위치(행렬에서)
        face_location = face_recognition.face_locations(frame) #cnn 모델 사용 X. 원할시, model='cnn' 입력(GPU 없는 기기에서는 실행되지 않음)
        top, right, bottom, left = face_location[0]
        print("A face is located at pixel location Top: {}, Left: {}, Bottom: {}, Right: {}".format(top, left, bottom, right))

        #face_location 찾아서 파일로 저장
        face_image = Image.fromarray(frame[top:bottom, left:right])
        #Image.fromarray(face_image).show()
        face_image.save(frame_save_path+'_D_002/%d.jpg' %count)
        print('Saved frame%d.jpg' %count)
        count += 1
        
    except :
        pass


video.release()
cv2.destroyAllWindows()

[[[183 195 207]
  [183 195 207]
  [180 196 207]
  ...
  [194 222 228]
  [190 222 228]
  [190 222 228]]

 [[183 195 207]
  [183 195 207]
  [180 196 207]
  ...
  [194 222 228]
  [190 222 228]
  [190 222 228]]

 [[180 196 207]
  [180 196 207]
  [178 196 207]
  ...
  [185 223 228]
  [182 224 228]
  [182 224 228]]

 ...

 [[ 44  31  44]
  [ 41  28  41]
  [ 22  25  35]
  ...
  [ 42  51  48]
  [ 52  61  58]
  [ 56  65  62]]

 [[ 42  30  40]
  [ 40  28  38]
  [ 28  25  33]
  ...
  [ 50  47  55]
  [ 52  53  74]
  [ 56  57  78]]

 [[ 42  30  40]
  [ 40  28  38]
  [ 29  26  34]
  ...
  [ 52  49  57]
  [ 50  51  72]
  [ 47  48  69]]]
[[[183 195 207]
  [183 195 207]
  [180 196 207]
  ...
  [194 222 228]
  [190 222 228]
  [190 222 228]]

 [[183 195 207]
  [183 195 207]
  [180 196 207]
  ...
  [194 222 228]
  [190 222 228]
  [190 222 228]]

 [[180 196 207]
  [180 196 207]
  [178 196 207]
  ...
  [185 223 228]
  [182 224 228]
  [182 224 228]]

 ...

 [[ 44  31  44]
  [ 41  28  41]
  [ 22  25  35]
  ..

[[[181 196 210]
  [181 196 210]
  [181 196 210]
  ...
  [210 218 229]
  [210 218 229]
  [210 218 229]]

 [[181 196 210]
  [181 196 210]
  [180 195 209]
  ...
  [210 218 229]
  [210 218 229]
  [210 218 229]]

 [[178 195 209]
  [178 195 209]
  [178 195 209]
  ...
  [210 218 229]
  [210 218 229]
  [210 218 229]]

 ...

 [[ 43  31  17]
  [ 43  31  17]
  [ 44  28  21]
  ...
  [ 56  72  49]
  [ 69  58  62]
  [ 68  57  61]]

 [[ 33  27  16]
  [ 34  28  17]
  [ 38  26  25]
  ...
  [ 63  65  63]
  [112  53  85]
  [106  47  79]]

 [[ 29  23  12]
  [ 31  25  14]
  [ 38  26  25]
  ...
  [ 64  66  64]
  [112  53  85]
  [115  56  88]]]
[[[177 194 208]
  [177 194 208]
  [178 195 209]
  ...
  [206 218 229]
  [206 218 229]
  [206 218 229]]

 [[177 194 208]
  [177 194 208]
  [177 194 208]
  ...
  [206 218 229]
  [206 218 229]
  [206 218 229]]

 [[178 193 207]
  [178 193 207]
  [177 194 208]
  ...
  [206 218 229]
  [206 218 229]
  [206 218 229]]

 ...

 [[ 44  32  41]
  [ 43  31  40]
  [ 31  24  38]
  ..

[[[172 193 208]
  [172 193 208]
  [159 197 209]
  ...
  [202 220 230]
  [202 220 230]
  [202 220 230]]

 [[172 193 208]
  [172 193 208]
  [159 197 209]
  ...
  [202 220 230]
  [202 220 230]
  [202 220 230]]

 [[181 191 208]
  [181 191 208]
  [169 194 208]
  ...
  [190 223 230]
  [190 223 230]
  [190 223 230]]

 ...

 [[ 52  22  31]
  [ 50  20  29]
  [ 38  23  30]
  ...
  [ 36  70  58]
  [ 56  67  52]
  [ 56  67  52]]

 [[ 49  22  29]
  [ 48  21  28]
  [ 28  22  27]
  ...
  [ 48  65  61]
  [ 76  62  54]
  [ 76  62  54]]

 [[ 48  21  28]
  [ 48  21  28]
  [ 28  22  27]
  ...
  [ 48  65  61]
  [ 76  62  54]
  [ 76  62  54]]]
[[[179 195 211]
  [179 195 211]
  [165 198 211]
  ...
  [199 220 229]
  [199 220 229]
  [199 220 229]]

 [[179 195 211]
  [179 195 211]
  [165 198 211]
  ...
  [199 220 229]
  [199 220 229]
  [199 220 229]]

 [[181 195 211]
  [181 195 211]
  [168 197 211]
  ...
  [199 220 229]
  [199 220 229]
  [199 220 229]]

 ...

 [[ 55  22  38]
  [ 54  21  37]
  [ 44  22  38]
  ..

[[[179 194 213]
  [179 194 213]
  [165 197 213]
  ...
  [208 222 228]
  [208 222 228]
  [208 222 228]]

 [[179 194 213]
  [179 194 213]
  [165 197 213]
  ...
  [208 222 228]
  [208 222 228]
  [208 222 228]]

 [[188 193 213]
  [188 193 213]
  [168 196 213]
  ...
  [208 222 228]
  [208 222 228]
  [208 222 228]]

 ...

 [[ 39  32  40]
  [ 40  33  41]
  [ 47  27  37]
  ...
  [ 61  56  70]
  [ 55  45  74]
  [ 58  48  77]]

 [[ 23  38  29]
  [ 22  37  28]
  [ 38  27  23]
  ...
  [ 71  66  74]
  [ 67  59  77]
  [ 57  49  67]]

 [[ 21  36  27]
  [ 21  36  27]
  [ 40  29  25]
  ...
  [ 79  74  82]
  [ 73  65  83]
  [ 56  48  66]]]
[[[173 196 209]
  [173 196 209]
  [159 199 209]
  ...
  [205 221 231]
  [205 221 231]
  [205 221 231]]

 [[173 196 209]
  [173 196 209]
  [159 199 209]
  ...
  [205 221 231]
  [205 221 231]
  [205 221 231]]

 [[183 194 209]
  [183 194 209]
  [164 198 209]
  ...
  [205 221 231]
  [205 221 231]
  [205 221 231]]

 ...

 [[ 37  28  26]
  [ 37  28  26]
  [ 47  32  33]
  ..

[[[183 191 208]
  [182 190 207]
  [175 189 205]
  ...
  [203 219 229]
  [202 218 228]
  [202 218 228]]

 [[183 191 208]
  [183 191 208]
  [176 190 206]
  ...
  [203 219 229]
  [202 218 228]
  [202 218 228]]

 [[177 193 209]
  [177 193 209]
  [169 194 208]
  ...
  [203 219 229]
  [202 218 228]
  [202 218 228]]

 ...

 [[ 36  46  45]
  [ 31  41  40]
  [ 25  29  29]
  ...
  [ 28  67  40]
  [ 26  64  45]
  [ 21  59  40]]

 [[ 31  32  28]
  [ 31  32  28]
  [ 32  28  27]
  ...
  [ 56  63  40]
  [ 27  60  39]
  [ 21  54  33]]

 [[ 27  28  24]
  [ 29  30  26]
  [ 32  28  27]
  ...
  [ 58  65  42]
  [ 23  56  35]
  [ 17  50  29]]]
[[[184 192 209]
  [184 192 209]
  [178 192 208]
  ...
  [206 218 229]
  [205 217 228]
  [205 217 228]]

 [[185 193 210]
  [185 193 210]
  [179 193 209]
  ...
  [206 218 229]
  [205 217 228]
  [205 217 228]]

 [[187 193 210]
  [187 193 210]
  [183 193 210]
  ...
  [206 218 229]
  [205 217 228]
  [205 217 228]]

 ...

 [[ 31  26  39]
  [ 37  32  45]
  [ 42  37  50]
  ..

[[[188 195 215]
  [181 188 208]
  [179 188 208]
  ...
  [204 220 231]
  [202 214 226]
  [201 213 225]]

 [[185 192 212]
  [183 190 210]
  [181 190 210]
  ...
  [204 220 231]
  [203 215 227]
  [201 213 225]]

 [[176 189 208]
  [178 191 210]
  [176 194 212]
  ...
  [204 220 231]
  [203 215 227]
  [202 214 226]]

 ...

 [[ 39  34  43]
  [ 39  34  43]
  [ 37  29  41]
  ...
  [ 59  57  68]
  [ 81  86  98]
  [ 93  98 110]]

 [[ 40  28  44]
  [ 40  28  44]
  [ 40  25  44]
  ...
  [ 59  41  58]
  [ 48  49  71]
  [ 42  43  65]]

 [[ 37  25  41]
  [ 37  25  41]
  [ 40  25  44]
  ...
  [ 41  23  40]
  [ 54  55  77]
  [ 58  59  81]]]
[[[190 195 215]
  [183 188 208]
  [181 188 208]
  ...
  [204 220 231]
  [202 214 226]
  [201 213 225]]

 [[188 193 213]
  [185 190 210]
  [183 190 210]
  ...
  [204 220 231]
  [203 215 227]
  [201 213 225]]

 [[180 189 209]
  [181 190 210]
  [180 193 212]
  ...
  [204 220 231]
  [203 215 227]
  [202 214 226]]

 ...

 [[ 17  32  28]
  [ 17  32  28]
  [ 22  26  26]
  ..

[[[177 193 204]
  [177 193 204]
  [181 195 206]
  ...
  [207 220 229]
  [207 220 229]
  [207 220 229]]

 [[178 194 205]
  [179 195 206]
  [181 195 206]
  ...
  [207 220 229]
  [207 220 229]
  [207 220 229]]

 [[178 196 207]
  [179 197 208]
  [181 197 208]
  ...
  [207 220 229]
  [207 220 229]
  [207 220 229]]

 ...

 [[ 23  30  19]
  [ 23  30  19]
  [ 28  31  20]
  ...
  [ 59  47 101]
  [ 66  49  93]
  [ 74  57 101]]

 [[ 16  29  14]
  [ 16  29  14]
  [ 21  29  15]
  ...
  [ 60  40  62]
  [ 74  31  76]
  [ 82  39  84]]

 [[ 21  34  19]
  [ 21  34  19]
  [ 24  32  18]
  ...
  [ 64  44  66]
  [ 78  35  80]
  [ 86  43  88]]]
[[[177 193 204]
  [177 193 204]
  [177 193 204]
  ...
  [207 220 229]
  [207 220 229]
  [207 220 229]]

 [[178 194 205]
  [178 194 205]
  [179 195 206]
  ...
  [207 220 229]
  [207 220 229]
  [207 220 229]]

 [[178 196 207]
  [178 196 207]
  [179 197 208]
  ...
  [207 220 229]
  [207 220 229]
  [207 220 229]]

 ...

 [[ 20  27  24]
  [ 23  30  27]
  [ 24  31  28]
  ..

[[[178 200 213]
  [176 198 211]
  [179 196 210]
  ...
  [209 219 230]
  [207 219 230]
  [207 219 230]]

 [[176 198 211]
  [175 197 210]
  [178 195 209]
  ...
  [209 219 230]
  [207 219 230]
  [207 219 230]]

 [[176 196 209]
  [175 195 208]
  [175 195 208]
  ...
  [209 219 230]
  [207 219 230]
  [207 219 230]]

 ...

 [[ 53  30  45]
  [ 43  20  35]
  [ 31  22  28]
  ...
  [ 68  55  40]
  [ 41  66  44]
  [ 41  66  44]]

 [[ 46  15  33]
  [ 34   3  21]
  [ 25   9  19]
  ...
  [106  81  72]
  [ 51  74  57]
  [ 43  66  49]]

 [[ 49  18  36]
  [ 42  11  29]
  [ 34  18  28]
  ...
  [ 91  66  57]
  [ 47  70  53]
  [ 46  69  52]]]
[[[180 199 214]
  [181 200 215]
  [182 198 214]
  ...
  [203 221 232]
  [202 220 231]
  [202 220 231]]

 [[178 197 212]
  [180 199 214]
  [181 197 213]
  ...
  [203 221 232]
  [202 220 231]
  [202 220 231]]

 [[174 195 210]
  [175 196 211]
  [175 196 211]
  ...
  [203 221 232]
  [202 220 231]
  [202 220 231]]

 ...

 [[ 38  30  42]
  [ 41  33  45]
  [ 38  30  42]
  ..

[[[176 194 212]
  [175 193 211]
  [164 194 210]
  ...
  [211 220 229]
  [208 217 226]
  [206 215 224]]

 [[175 193 211]
  [175 193 211]
  [164 194 210]
  ...
  [211 220 229]
  [208 217 226]
  [207 216 225]]

 [[170 194 211]
  [170 194 211]
  [160 194 210]
  ...
  [211 220 229]
  [208 217 226]
  [207 216 225]]

 ...

 [[ 51  22  34]
  [ 46  17  29]
  [ 36  22  35]
  ...
  [ 63  43  65]
  [ 58  47  79]
  [ 60  49  81]]

 [[ 41  28  31]
  [ 37  24  27]
  [ 32  23  29]
  ...
  [ 40  51  66]
  [ 74  44  85]
  [ 76  46  87]]

 [[ 50  37  40]
  [ 41  28  31]
  [ 30  21  27]
  ...
  [ 57  68  83]
  [ 81  51  92]
  [ 79  49  90]]]
[[[181 194 213]
  [180 193 212]
  [172 193 211]
  ...
  [207 220 229]
  [204 217 226]
  [202 215 224]]

 [[180 193 212]
  [179 192 211]
  [172 193 211]
  ...
  [207 220 229]
  [204 217 226]
  [203 216 225]]

 [[170 194 211]
  [170 194 211]
  [165 195 211]
  ...
  [207 220 229]
  [204 217 226]
  [203 216 225]]

 ...

 [[ 44  22  28]
  [ 49  27  33]
  [ 48  33  40]
  ..

[[[253 253 251]
  [253 253 251]
  [253 253 251]
  ...
  [255 253 255]
  [255 253 255]
  [255 253 255]]

 [[253 253 251]
  [253 253 251]
  [253 253 251]
  ...
  [255 253 255]
  [255 253 255]
  [255 253 255]]

 [[253 253 253]
  [253 253 253]
  [251 253 253]
  ...
  [255 253 255]
  [255 253 255]
  [255 253 255]]

 ...

 [[ 75  70  59]
  [ 65  60  49]
  [ 44  55  40]
  ...
  [ 99 116 106]
  [104 101 120]
  [100  97 116]]

 [[ 79  74  62]
  [ 70  65  53]
  [ 53  61  48]
  ...
  [108 118 113]
  [116 101 138]
  [112  97 134]]

 [[ 84  79  67]
  [ 79  74  62]
  [ 64  72  59]
  ...
  [116 126 121]
  [125 110 147]
  [124 109 146]]]
[[[253 253 251]
  [253 253 251]
  [253 253 251]
  ...
  [255 253 255]
  [255 253 255]
  [255 253 255]]

 [[253 253 251]
  [253 253 251]
  [253 253 251]
  ...
  [255 253 255]
  [255 253 255]
  [255 253 255]]

 [[253 253 253]
  [253 253 253]
  [251 253 253]
  ...
  [255 253 255]
  [255 253 255]
  [255 253 255]]

 ...

 [[ 84  68  61]
  [ 81  65  58]
  [ 76  57  59]
  ..

[[[251 255 253]
  [251 255 253]
  [251 255 253]
  ...
  [255 253 255]
  [255 253 255]
  [255 253 255]]

 [[251 255 253]
  [251 255 253]
  [251 255 253]
  ...
  [255 253 255]
  [255 253 255]
  [255 253 255]]

 [[251 255 255]
  [251 255 255]
  [249 255 255]
  ...
  [255 253 255]
  [255 253 255]
  [255 253 255]]

 ...

 [[ 38  30  80]
  [ 44  36  86]
  [ 49  46 103]
  ...
  [107 138  97]
  [ 97 134  87]
  [ 97 134  87]]

 [[ 46  46  88]
  [ 47  47  89]
  [ 45  49 101]
  ...
  [105 123  97]
  [ 87 122  89]
  [ 93 128  95]]

 [[ 61  61 103]
  [ 64  64 106]
  [ 65  69 121]
  ...
  [107 125  99]
  [ 92 127  94]
  [107 142 109]]]
[[[238 253 249]
  [238 253 249]
  [238 253 249]
  ...
  [255 253 255]
  [255 253 255]
  [255 253 255]]

 [[238 253 249]
  [238 253 249]
  [238 253 249]
  ...
  [255 253 255]
  [255 253 255]
  [255 253 255]]

 [[238 253 251]
  [238 253 251]
  [236 253 251]
  ...
  [255 253 255]
  [255 253 255]
  [255 253 255]]

 ...

 [[ 23  51  79]
  [ 20  48  76]
  [ 24  36  72]
  ..

[[[226 244 248]
  [226 244 248]
  [225 243 248]
  ...
  [248 255 254]
  [248 255 254]
  [248 255 254]]

 [[226 244 248]
  [226 244 248]
  [225 243 248]
  ...
  [248 255 254]
  [248 255 254]
  [248 255 254]]

 [[220 245 248]
  [220 245 248]
  [219 244 248]
  ...
  [248 255 254]
  [248 255 254]
  [248 255 254]]

 ...

 [[ 61  48  43]
  [ 61  48  43]
  [ 40  24  35]
  ...
  [ 78  78  76]
  [ 91  80  76]
  [ 95  84  80]]

 [[ 39  36  24]
  [ 42  39  27]
  [ 35  28  36]
  ...
  [ 86  84  88]
  [112  84  89]
  [115  87  92]]

 [[ 35  32  20]
  [ 38  35  23]
  [ 44  37  45]
  ...
  [ 96  94  98]
  [116  88  93]
  [118  90  95]]]
[[[226 244 248]
  [226 244 248]
  [225 243 248]
  ...
  [248 255 254]
  [248 255 254]
  [248 255 254]]

 [[226 244 248]
  [226 244 248]
  [225 243 248]
  ...
  [248 255 254]
  [248 255 254]
  [248 255 254]]

 [[220 245 248]
  [220 245 248]
  [219 244 248]
  ...
  [248 255 254]
  [248 255 254]
  [248 255 254]]

 ...

 [[ 55  39  44]
  [ 57  41  46]
  [ 56  40  51]
  ..

[[[223 235 246]
  [224 236 247]
  [224 238 248]
  ...
  [248 255 254]
  [248 255 254]
  [248 255 254]]

 [[223 235 246]
  [223 235 246]
  [223 237 247]
  ...
  [248 255 254]
  [248 255 254]
  [248 255 254]]

 [[220 236 246]
  [220 236 246]
  [221 237 247]
  ...
  [248 255 254]
  [248 255 254]
  [248 255 254]]

 ...

 [[ 33  42  39]
  [ 33  42  39]
  [ 41  41  39]
  ...
  [106  88  99]
  [109  80  93]
  [104  75  88]]

 [[ 36  43  40]
  [ 36  43  40]
  [ 38  42  40]
  ...
  [106  87 101]
  [110  80  96]
  [102  72  88]]

 [[ 35  42  39]
  [ 34  41  38]
  [ 36  40  38]
  ...
  [107  88 102]
  [110  80  96]
  [101  71  87]]]
[[[218 238 243]
  [219 239 244]
  [216 241 245]
  ...
  [248 255 254]
  [248 255 254]
  [248 255 254]]

 [[218 238 243]
  [218 238 243]
  [215 240 244]
  ...
  [248 255 254]
  [248 255 254]
  [248 255 254]]

 [[214 239 243]
  [214 239 243]
  [214 240 244]
  ...
  [248 255 254]
  [248 255 254]
  [248 255 254]]

 ...

 [[ 45  44  52]
  [ 46  45  53]
  [ 47  44  52]
  ..

[[[179 202 215]
  [178 201 214]
  [187 198 213]
  ...
  [208 224 229]
  [208 224 229]
  [208 224 229]]

 [[179 202 215]
  [178 201 214]
  [187 198 213]
  ...
  [208 224 229]
  [208 224 229]
  [208 224 229]]

 [[179 202 215]
  [178 201 214]
  [187 198 213]
  ...
  [208 224 229]
  [208 224 229]
  [208 224 229]]

 ...

 [[ 41  26  33]
  [ 38  23  30]
  [ 20  25  28]
  ...
  [ 63  52  58]
  [ 70  43  75]
  [ 68  41  73]]

 [[ 41  31  35]
  [ 40  30  34]
  [ 24  30  31]
  ...
  [ 68  52  63]
  [ 75  38  88]
  [ 74  37  87]]

 [[ 28  18  22]
  [ 31  21  25]
  [ 22  28  29]
  ...
  [ 69  53  64]
  [ 77  40  90]
  [ 77  40  90]]]
[[[174 196 211]
  [174 196 211]
  [180 194 210]
  ...
  [204 222 227]
  [204 222 227]
  [204 222 227]]

 [[173 195 210]
  [174 196 211]
  [180 194 210]
  ...
  [204 222 227]
  [204 222 227]
  [204 222 227]]

 [[170 195 209]
  [170 195 209]
  [179 193 209]
  ...
  [202 220 225]
  [202 220 225]
  [202 220 225]]

 ...

 [[ 30  25  39]
  [ 31  26  40]
  [ 32  27  41]
  ..

[[[177 198 208]
  [177 198 208]
  [185 195 207]
  ...
  [197 220 233]
  [197 220 233]
  [197 220 233]]

 [[175 196 206]
  [176 197 207]
  [185 195 207]
  ...
  [197 220 233]
  [197 220 233]
  [197 220 233]]

 [[173 196 206]
  [173 196 206]
  [182 194 206]
  ...
  [200 220 233]
  [200 220 233]
  [200 220 233]]

 ...

 [[ 22  38  38]
  [ 23  39  39]
  [ 21  43  42]
  ...
  [ 66  59  25]
  [ 85  55  54]
  [101  71  70]]

 [[ 10  29  30]
  [ 13  32  33]
  [  2  23  24]
  ...
  [ 64  57  23]
  [ 84  52  40]
  [ 81  49  37]]

 [[  9  28  29]
  [ 11  30  31]
  [ 15  36  37]
  ...
  [ 75  68  34]
  [ 88  56  44]
  [ 82  50  38]]]
[[[170 198 210]
  [170 198 210]
  [178 195 209]
  ...
  [193 222 230]
  [193 222 230]
  [193 222 230]]

 [[169 197 209]
  [169 197 209]
  [178 195 209]
  ...
  [193 222 230]
  [193 222 230]
  [193 222 230]]

 [[172 195 208]
  [172 195 208]
  [180 195 209]
  ...
  [197 221 230]
  [197 221 230]
  [197 221 230]]

 ...

 [[ 19  31  47]
  [ 19  31  47]
  [ 12  30  49]
  ..

[[[180 201 211]
  [178 199 209]
  [176 197 207]
  ...
  [205 219 229]
  [205 220 228]
  [205 220 228]]

 [[179 200 210]
  [178 199 209]
  [176 197 207]
  ...
  [204 218 228]
  [204 219 227]
  [204 219 227]]

 [[179 197 208]
  [178 196 207]
  [177 195 206]
  ...
  [204 216 227]
  [204 216 227]
  [204 216 227]]

 ...

 [[ 27  37  36]
  [ 26  36  35]
  [ 24  34  39]
  ...
  [ 66  60  48]
  [ 79  60  42]
  [ 88  69  51]]

 [[ 25  35  30]
  [ 24  34  29]
  [ 28  31  33]
  ...
  [ 79  56  50]
  [ 66  63  43]
  [ 75  72  52]]

 [[ 22  32  27]
  [ 21  31  26]
  [ 25  28  30]
  ...
  [ 70  47  41]
  [ 57  54  34]
  [ 66  63  43]]]
[[[189 203 214]
  [186 200 211]
  [182 196 207]
  ...
  [205 220 228]
  [205 221 226]
  [205 221 226]]

 [[187 201 212]
  [185 199 210]
  [182 196 207]
  ...
  [204 219 227]
  [204 220 225]
  [204 220 225]]

 [[183 199 210]
  [181 197 208]
  [179 195 206]
  ...
  [204 217 226]
  [204 217 226]
  [204 217 226]]

 ...

 [[ 35  34  31]
  [ 35  34  31]
  [ 33  31  35]
  ..

[[[167 199 210]
  [169 201 212]
  [166 200 211]
  ...
  [210 220 225]
  [210 220 225]
  [210 220 225]]

 [[167 199 210]
  [169 201 212]
  [166 200 211]
  ...
  [210 220 225]
  [210 220 225]
  [210 220 225]]

 [[170 196 208]
  [172 198 210]
  [170 198 210]
  ...
  [206 220 225]
  [206 220 225]
  [206 220 225]]

 ...

 [[ 40  36  47]
  [ 37  33  44]
  [ 33  27  44]
  ...
  [ 48  60  42]
  [ 46  56  53]
  [ 41  51  48]]

 [[ 29  29  47]
  [ 28  28  46]
  [ 26  24  48]
  ...
  [ 49  54  57]
  [ 44  40  62]
  [ 51  47  69]]

 [[ 26  26  44]
  [ 26  26  44]
  [ 26  24  48]
  ...
  [ 69  74  77]
  [ 55  51  73]
  [ 60  56  78]]]
[[[164 192 204]
  [168 196 208]
  [168 198 210]
  ...
  [205 221 225]
  [205 221 225]
  [205 221 225]]

 [[165 193 205]
  [168 196 208]
  [168 198 210]
  ...
  [205 221 225]
  [205 221 225]
  [205 221 225]]

 [[165 191 203]
  [169 195 207]
  [169 197 209]
  ...
  [203 221 225]
  [203 221 225]
  [203 221 225]]

 ...

 [[ 34  45  36]
  [ 28  39  30]
  [ 19  28  25]
  ..

[[[171 196 210]
  [171 196 210]
  [190 193 211]
  ...
  [206 220 226]
  [206 220 226]
  [206 220 226]]

 [[171 196 210]
  [171 196 210]
  [190 193 211]
  ...
  [206 220 226]
  [206 220 226]
  [206 220 226]]

 [[166 195 209]
  [166 195 209]
  [174 196 211]
  ...
  [206 220 226]
  [206 220 226]
  [206 220 226]]

 ...

 [[ 38  37  34]
  [ 35  34  31]
  [ 33  27  32]
  ...
  [ 45  65  58]
  [ 49  67  61]
  [ 49  67  61]]

 [[ 30  29  36]
  [ 30  29  36]
  [ 29  27  38]
  ...
  [ 52  71  62]
  [ 64  73  72]
  [ 58  67  66]]

 [[ 26  25  32]
  [ 29  28  35]
  [ 31  29  40]
  ...
  [ 55  74  65]
  [ 68  77  76]
  [ 60  69  68]]]
[[[174 195 210]
  [174 195 210]
  [190 193 211]
  ...
  [215 219 226]
  [215 219 226]
  [215 219 226]]

 [[174 195 210]
  [174 195 210]
  [190 193 211]
  ...
  [215 219 226]
  [215 219 226]
  [215 219 226]]

 [[177 193 209]
  [177 193 209]
  [183 195 211]
  ...
  [210 220 226]
  [210 220 226]
  [210 220 226]]

 ...

 [[ 33  27  32]
  [ 32  26  31]
  [ 37  27  31]
  ..

[[[175 196 205]
  [174 195 204]
  [178 194 204]
  ...
  [200 221 230]
  [207 221 231]
  [210 224 234]]

 [[175 196 205]
  [175 196 205]
  [178 194 204]
  ...
  [200 221 230]
  [207 221 231]
  [209 223 233]]

 [[177 195 205]
  [177 195 205]
  [178 194 204]
  ...
  [200 221 230]
  [205 221 231]
  [206 222 232]]

 ...

 [[ 42  28  44]
  [ 40  26  42]
  [ 40  22  49]
  ...
  [ 59  61  59]
  [ 43  60  56]
  [ 40  57  53]]

 [[ 32  26  38]
  [ 31  25  37]
  [ 33  23  47]
  ...
  [ 62  62  60]
  [ 48  63  59]
  [ 46  61  57]]

 [[ 28  22  34]
  [ 33  27  39]
  [ 34  24  48]
  ...
  [ 63  63  61]
  [ 50  65  61]
  [ 49  64  60]]]
[[[173 197 206]
  [172 196 205]
  [182 194 205]
  ...
  [204 220 230]
  [210 220 231]
  [213 223 234]]

 [[172 196 205]
  [172 196 205]
  [181 193 204]
  ...
  [204 220 230]
  [210 220 231]
  [212 222 233]]

 [[172 196 205]
  [172 196 205]
  [180 194 204]
  ...
  [204 220 230]
  [208 220 231]
  [209 221 232]]

 ...

 [[ 49  26  46]
  [ 49  26  46]
  [ 50  25  50]
  ..

[[[165 197 208]
  [164 196 207]
  [167 195 207]
  ...
  [194 224 230]
  [199 223 230]
  [199 223 230]]

 [[165 197 208]
  [165 197 208]
  [167 195 207]
  ...
  [194 224 230]
  [199 223 230]
  [198 222 229]]

 [[172 195 208]
  [172 195 208]
  [169 195 207]
  ...
  [196 224 230]
  [199 223 230]
  [198 222 229]]

 ...

 [[ 36  24  34]
  [ 47  35  45]
  [ 54  40  56]
  ...
  [ 58  67  50]
  [ 60  65  44]
  [ 54  59  38]]

 [[ 45  38  32]
  [ 47  40  34]
  [ 51  42  42]
  ...
  [ 56  59  61]
  [ 58  56  55]
  [ 50  48  47]]

 [[ 42  35  29]
  [ 35  28  22]
  [ 42  33  33]
  ...
  [ 55  58  60]
  [ 56  54  53]
  [ 49  47  46]]]
[[[165 195 207]
  [165 195 207]
  [172 194 207]
  ...
  [198 223 230]
  [203 222 230]
  [203 222 230]]

 [[166 196 208]
  [165 195 207]
  [172 194 207]
  ...
  [198 223 230]
  [203 222 230]
  [202 221 229]]

 [[170 196 208]
  [169 195 207]
  [172 195 208]
  ...
  [199 223 230]
  [203 222 230]
  [202 221 229]]

 ...

 [[ 30  25  34]
  [ 37  32  41]
  [ 41  36  45]
  ..

[[[176 194 205]
  [176 194 205]
  [180 194 205]
  ...
  [207 218 227]
  [209 220 229]
  [209 220 229]]

 [[178 196 207]
  [176 194 205]
  [181 195 206]
  ...
  [207 218 227]
  [209 220 229]
  [209 220 229]]

 [[182 194 206]
  [182 194 206]
  [182 194 206]
  ...
  [208 219 228]
  [209 220 229]
  [209 220 229]]

 ...

 [[ 34  31  34]
  [ 29  26  29]
  [ 37  26  32]
  ...
  [ 89  79  83]
  [ 59  58  65]
  [ 53  52  59]]

 [[ 26  30  30]
  [ 29  33  33]
  [ 36  31  34]
  ...
  [ 98  82  87]
  [ 71  66  79]
  [ 64  59  72]]

 [[ 24  28  28]
  [ 31  35  35]
  [ 33  28  31]
  ...
  [100  84  89]
  [ 74  69  82]
  [ 69  64  77]]]
[[[176 194 205]
  [176 194 205]
  [180 194 205]
  ...
  [207 219 224]
  [209 221 226]
  [209 221 226]]

 [[178 196 207]
  [176 194 205]
  [181 195 206]
  ...
  [207 219 224]
  [209 221 226]
  [209 221 226]]

 [[182 194 206]
  [182 194 206]
  [182 194 206]
  ...
  [208 220 225]
  [209 221 226]
  [209 221 226]]

 ...

 [[ 32  29  42]
  [ 30  27  40]
  [ 34  29  42]
  ..

[[[172 195 208]
  [171 194 207]
  [168 196 208]
  ...
  [207 220 229]
  [207 220 229]
  [207 220 229]]

 [[173 196 209]
  [172 195 208]
  [168 196 208]
  ...
  [207 220 229]
  [207 220 229]
  [207 220 229]]

 [[175 195 208]
  [175 195 208]
  [170 196 208]
  ...
  [207 220 229]
  [207 220 229]
  [207 220 229]]

 ...

 [[ 46  24  24]
  [ 48  26  26]
  [ 27  23  22]
  ...
  [ 70  52  77]
  [ 19  66  69]
  [ 19  66  69]]

 [[ 39  23  28]
  [ 41  25  30]
  [ 25  24  26]
  ...
  [ 61  58  71]
  [ 24  70  63]
  [ 24  70  63]]

 [[ 39  23  28]
  [ 41  25  30]
  [ 26  25  27]
  ...
  [ 62  59  72]
  [ 25  71  64]
  [ 25  71  64]]]
[[[175 193 211]
  [174 192 210]
  [172 193 211]
  ...
  [202 221 229]
  [202 221 229]
  [202 221 229]]

 [[176 194 212]
  [175 193 211]
  [172 193 211]
  ...
  [202 221 229]
  [202 221 229]
  [202 221 229]]

 [[180 193 212]
  [179 192 211]
  [173 193 211]
  ...
  [202 221 229]
  [202 221 229]
  [202 221 229]]

 ...

 [[ 23  28  24]
  [ 24  29  25]
  [ 18  28  25]
  ..

[[[175 193 211]
  [175 193 211]
  [175 193 211]
  ...
  [205 219 229]
  [205 219 229]
  [205 219 229]]

 [[175 193 211]
  [176 194 212]
  [175 193 211]
  ...
  [205 219 229]
  [205 219 229]
  [205 219 229]]

 [[179 192 211]
  [180 193 212]
  [178 193 212]
  ...
  [205 219 229]
  [205 219 229]
  [205 219 229]]

 ...

 [[ 58  38  38]
  [ 58  38  38]
  [ 37  37  37]
  ...
  [ 75  58  34]
  [ 81  53  40]
  [ 84  56  43]]

 [[ 50  37  33]
  [ 49  36  32]
  [ 23  28  24]
  ...
  [ 63  57  38]
  [ 73  53  46]
  [ 75  55  48]]

 [[ 30  17  13]
  [ 38  25  21]
  [ 25  30  26]
  ...
  [ 63  57  38]
  [ 74  54  47]
  [ 76  56  49]]]
[[[160 194 210]
  [160 194 210]
  [166 194 211]
  ...
  [195 219 229]
  [195 219 229]
  [195 219 229]]

 [[162 196 212]
  [162 196 212]
  [166 194 211]
  ...
  [195 219 229]
  [195 219 229]
  [195 219 229]]

 [[179 192 211]
  [179 192 211]
  [179 192 211]
  ...
  [195 219 229]
  [195 219 229]
  [195 219 229]]

 ...

 [[ 33  28  22]
  [ 33  28  22]
  [ 32  27  22]
  ..

[[[180 195 209]
  [180 195 209]
  [180 195 209]
  ...
  [196 220 227]
  [196 220 227]
  [196 220 227]]

 [[180 195 209]
  [180 195 209]
  [180 195 209]
  ...
  [197 221 228]
  [197 221 228]
  [196 220 227]]

 [[179 194 208]
  [179 194 208]
  [180 195 209]
  ...
  [198 222 229]
  [198 222 229]
  [197 221 228]]

 ...

 [[ 39  26  27]
  [ 40  27  28]
  [ 40  29  25]
  ...
  [ 50  62  44]
  [  7  24   0]
  [ 24  41  15]]

 [[ 45  35  35]
  [ 35  25  25]
  [ 30  27  24]
  ...
  [ 30  72  42]
  [ 19  84  33]
  [  6  71  20]]

 [[ 33  23  23]
  [ 33  23  23]
  [ 28  25  22]
  ...
  [ 33  75  45]
  [ 22  87  36]
  [ 23  88  37]]]
[[[189 193 209]
  [189 193 209]
  [185 194 209]
  ...
  [204 218 229]
  [204 218 229]
  [204 218 229]]

 [[189 193 209]
  [189 193 209]
  [185 194 209]
  ...
  [205 219 230]
  [205 219 230]
  [204 218 229]]

 [[184 193 208]
  [184 193 208]
  [183 194 209]
  ...
  [206 220 231]
  [206 220 231]
  [205 219 230]]

 ...

 [[ 66  21  36]
  [ 73  28  43]
  [ 52  34  44]
  ..

[[[169 195 212]
  [170 196 213]
  [167 195 212]
  ...
  [208 220 226]
  [208 220 226]
  [208 220 226]]

 [[169 195 212]
  [170 196 213]
  [168 196 213]
  ...
  [208 220 226]
  [208 220 226]
  [208 220 226]]

 [[167 197 213]
  [167 197 213]
  [168 198 214]
  ...
  [208 220 226]
  [208 220 226]
  [208 220 226]]

 ...

 [[ 39  17  33]
  [ 39  17  33]
  [ 37  15  32]
  ...
  [ 38  69  71]
  [ 57  61  67]
  [ 61  65  71]]

 [[ 52  22  31]
  [ 55  25  34]
  [ 50  21  34]
  ...
  [ 36  58  65]
  [ 57  54  67]
  [ 53  50  63]]

 [[ 44  14  23]
  [ 53  23  32]
  [ 51  22  35]
  ...
  [ 39  61  68]
  [ 54  51  64]
  [ 55  52  65]]]
[[[160 195 208]
  [161 196 209]
  [165 196 209]
  ...
  [201 219 230]
  [200 221 231]
  [200 221 231]]

 [[161 196 209]
  [162 197 210]
  [167 198 211]
  ...
  [201 219 230]
  [200 221 231]
  [200 221 231]]

 [[162 197 210]
  [163 198 211]
  [166 199 212]
  ...
  [199 220 230]
  [198 221 231]
  [198 221 231]]

 ...

 [[ 41  37  28]
  [ 37  33  24]
  [ 31  24  19]
  ..

[[[159 198 208]
  [160 199 209]
  [169 199 211]
  ...
  [203 222 230]
  [202 221 229]
  [201 220 228]]

 [[160 199 209]
  [160 199 209]
  [169 199 211]
  ...
  [202 221 229]
  [201 220 228]
  [201 220 228]]

 [[182 195 209]
  [182 195 209]
  [182 197 211]
  ...
  [202 221 229]
  [201 220 228]
  [201 220 228]]

 ...

 [[ 45  16  37]
  [ 46  17  38]
  [ 43  18  39]
  ...
  [ 53  41  22]
  [ 37  48  19]
  [ 41  52  23]]

 [[ 55  17  40]
  [ 56  18  41]
  [ 49  15  37]
  ...
  [ 63  44  41]
  [ 40  54  40]
  [ 44  58  44]]

 [[ 54  16  39]
  [ 54  16  39]
  [ 48  14  36]
  ...
  [ 76  57  54]
  [ 58  72  58]
  [ 74  88  74]]]
A face is located at pixel location Top: 266, Left: 637, Bottom: 489, Right: 860
[[[167 196 210]
  [168 197 211]
  [168 197 211]
  ...
  [207 222 230]
  [206 221 229]
  [205 220 228]]

 [[169 198 212]
  [169 198 212]
  [169 198 212]
  ...
  [206 221 229]
  [205 220 228]
  [205 220 228]]

 [[176 198 213]
  [176 198 213]
  [170 199 213]
  ...
  [206 221 229]
  [205 220 

[[[197 194 208]
  [196 193 207]
  [185 195 207]
  ...
  [202 219 227]
  [197 219 226]
  [197 219 226]]

 [[197 194 208]
  [196 193 207]
  [185 195 207]
  ...
  [203 220 228]
  [196 218 225]
  [197 219 226]]

 [[189 194 207]
  [189 194 207]
  [179 195 206]
  ...
  [203 220 228]
  [197 219 226]
  [195 217 224]]

 ...

 [[ 49  22  37]
  [ 47  20  35]
  [ 29  23  35]
  ...
  [ 51  63  74]
  [ 54  66  77]
  [ 58  70  81]]

 [[ 67  26  41]
  [ 66  25  40]
  [ 44  22  34]
  ...
  [ 65  60  79]
  [ 67  60  79]
  [ 71  64  83]]

 [[ 69  28  43]
  [ 67  26  41]
  [ 45  23  35]
  ...
  [ 63  58  77]
  [ 58  51  70]
  [ 61  54  73]]]
[[[200 190 213]
  [199 189 212]
  [189 191 212]
  ...
  [205 218 227]
  [201 218 226]
  [201 218 226]]

 [[200 190 213]
  [199 189 212]
  [189 191 212]
  ...
  [206 219 228]
  [200 217 225]
  [201 218 226]]

 [[189 190 211]
  [189 190 211]
  [181 192 211]
  ...
  [206 219 228]
  [201 218 226]
  [199 216 224]]

 ...

 [[ 42  30  36]
  [ 39  27  33]
  [ 40  28  34]
  ..

[[[170 198 215]
  [169 197 214]
  [170 196 213]
  ...
  [214 217 227]
  [211 216 226]
  [211 216 226]]

 [[170 198 215]
  [169 197 214]
  [171 197 214]
  ...
  [214 217 227]
  [210 215 225]
  [211 216 226]]

 [[169 195 212]
  [169 195 212]
  [162 196 212]
  ...
  [213 218 228]
  [210 216 226]
  [208 214 224]]

 ...

 [[ 66  37  42]
  [ 65  36  41]
  [ 58  35  39]
  ...
  [ 55  54  67]
  [ 74  56  66]
  [ 75  57  67]]

 [[ 32  27  35]
  [ 32  27  35]
  [ 30  27  34]
  ...
  [ 37  54  84]
  [ 59  53  82]
  [ 60  54  83]]

 [[ 33  28  36]
  [ 32  27  35]
  [ 29  26  33]
  ...
  [ 39  56  86]
  [ 61  55  84]
  [ 61  55  84]]]
[[[184 195 214]
  [184 195 214]
  [179 194 213]
  ...
  [214 217 227]
  [211 216 226]
  [211 216 226]]

 [[185 196 215]
  [185 196 215]
  [180 195 214]
  ...
  [214 217 227]
  [210 215 225]
  [211 216 226]]

 [[175 196 214]
  [175 196 214]
  [171 197 214]
  ...
  [213 218 228]
  [210 216 226]
  [208 214 224]]

 ...

 [[ 38  39  35]
  [ 38  39  35]
  [ 38  39  35]
  ..

[[[171 197 214]
  [170 196 213]
  [168 196 213]
  ...
  [197 222 226]
  [197 222 226]
  [197 222 226]]

 [[171 197 214]
  [171 197 214]
  [169 197 214]
  ...
  [197 222 226]
  [197 222 226]
  [197 222 226]]

 [[175 195 213]
  [175 195 213]
  [168 196 213]
  ...
  [197 222 226]
  [197 222 226]
  [197 222 226]]

 ...

 [[ 21  17  28]
  [ 26  22  33]
  [ 36  29  38]
  ...
  [ 64  63  65]
  [ 64  54  82]
  [ 63  53  81]]

 [[ 21  15  27]
  [ 25  19  31]
  [ 31  24  32]
  ...
  [ 60  64  64]
  [ 66  61  75]
  [ 66  61  75]]

 [[ 23  17  29]
  [ 26  20  32]
  [ 30  23  31]
  ...
  [ 60  64  64]
  [ 67  62  76]
  [ 67  62  76]]]
[[[165 199 215]
  [164 198 214]
  [173 197 214]
  ...
  [197 222 226]
  [197 222 226]
  [197 222 226]]

 [[165 199 215]
  [165 199 215]
  [173 197 214]
  ...
  [197 222 226]
  [197 222 226]
  [197 222 226]]

 [[175 195 213]
  [175 195 213]
  [175 195 213]
  ...
  [197 222 226]
  [197 222 226]
  [197 222 226]]

 ...

 [[ 29  26  54]
  [ 33  30  58]
  [ 32  27  52]
  ..

A face is located at pixel location Top: 231, Left: 587, Bottom: 498, Right: 854
[[[174 193 208]
  [174 193 208]
  [171 193 208]
  ...
  [199 220 229]
  [197 218 227]
  [195 216 225]]

 [[175 194 209]
  [175 194 209]
  [172 194 209]
  ...
  [199 220 229]
  [198 219 228]
  [196 217 226]]

 [[181 193 209]
  [181 193 209]
  [175 194 209]
  ...
  [198 221 230]
  [197 220 229]
  [195 218 227]]

 ...

 [[ 68  34  33]
  [ 62  28  27]
  [ 34  31  28]
  ...
  [ 48  52  58]
  [ 36  49  63]
  [ 36  49  63]]

 [[ 79  35  36]
  [ 72  28  29]
  [ 36  27  27]
  ...
  [ 56  57  73]
  [ 51  57  87]
  [ 55  61  91]]

 [[ 78  34  35]
  [ 70  26  27]
  [ 32  23  23]
  ...
  [ 61  62  78]
  [ 53  59  89]
  [ 51  57  87]]]
A face is located at pixel location Top: 231, Left: 587, Bottom: 498, Right: 854
[[[176 192 208]
  [176 192 208]
  [172 193 208]
  ...
  [208 218 229]
  [206 216 227]
  [204 214 225]]

 [[177 193 209]
  [177 193 209]
  [173 194 209]
  ...
  [208 218 229]
  [207 217 228]
  [205 215 226]]



[[[182 197 216]
  [181 196 215]
  [181 194 213]
  ...
  [209 221 232]
  [209 221 232]
  [207 219 230]]

 [[181 196 215]
  [180 195 214]
  [181 194 213]
  ...
  [209 221 232]
  [209 221 232]
  [207 219 230]]

 [[171 192 210]
  [174 195 213]
  [177 195 213]
  ...
  [203 221 232]
  [203 221 232]
  [202 220 231]]

 ...

 [[ 26  26  19]
  [ 32  32  25]
  [ 35  35  29]
  ...
  [ 56  64  45]
  [ 55  63  44]
  [ 55  63  44]]

 [[ 33  25  20]
  [ 36  28  23]
  [ 34  28  26]
  ...
  [ 50  65  47]
  [ 50  65  47]
  [ 50  65  47]]

 [[ 35  27  22]
  [ 33  25  20]
  [ 30  24  22]
  ...
  [ 52  67  49]
  [ 52  67  49]
  [ 52  67  49]]]
[[[191 193 214]
  [190 192 213]
  [189 190 211]
  ...
  [198 221 230]
  [198 221 230]
  [196 219 228]]

 [[191 193 214]
  [189 191 212]
  [190 191 212]
  ...
  [198 221 230]
  [198 221 230]
  [196 219 228]]

 [[181 190 210]
  [184 193 213]
  [187 192 212]
  ...
  [198 221 231]
  [198 221 231]
  [197 220 230]]

 ...

 [[ 12  32  31]
  [ 13  33  32]
  [  7  28  29]
  ..

[[[162 194 210]
  [162 194 210]
  [168 194 211]
  ...
  [209 220 229]
  [206 217 226]
  [206 217 226]]

 [[163 195 211]
  [163 195 211]
  [169 195 212]
  ...
  [209 220 229]
  [207 218 227]
  [207 218 227]]

 [[170 194 211]
  [171 195 212]
  [176 194 212]
  ...
  [206 220 230]
  [205 219 229]
  [205 219 229]]

 ...

 [[ 26  30  28]
  [ 26  30  28]
  [ 26  30  28]
  ...
  [ 38  52  34]
  [ 33  59  39]
  [ 36  62  42]]

 [[ 29  25  30]
  [ 29  25  30]
  [ 29  25  30]
  ...
  [ 57  74  59]
  [ 51  81  64]
  [ 54  84  67]]

 [[ 29  25  30]
  [ 29  25  30]
  [ 29  25  30]
  ...
  [ 61  78  63]
  [ 43  73  56]
  [ 41  71  54]]]
[[[160 194 210]
  [160 194 210]
  [170 194 211]
  ...
  [206 221 229]
  [203 218 226]
  [203 218 226]]

 [[161 195 211]
  [161 195 211]
  [171 195 212]
  ...
  [206 221 229]
  [204 219 227]
  [204 219 227]]

 [[168 194 211]
  [169 195 212]
  [176 194 212]
  ...
  [202 220 230]
  [201 219 229]
  [201 219 229]]

 ...

 [[ 36  34  35]
  [ 37  35  36]
  [ 38  36  37]
  ..

[[[175 195 208]
  [176 196 209]
  [182 195 209]
  ...
  [207 220 229]
  [207 220 229]
  [207 220 229]]

 [[173 193 206]
  [173 193 206]
  [181 194 208]
  ...
  [208 221 230]
  [208 221 230]
  [208 221 230]]

 [[172 194 207]
  [172 194 207]
  [176 193 207]
  ...
  [205 221 231]
  [205 221 231]
  [205 221 231]]

 ...

 [[ 39  26  45]
  [ 38  25  44]
  [ 42  23  43]
  ...
  [ 50  63  34]
  [ 47  63  33]
  [ 46  62  32]]

 [[ 36  20  41]
  [ 36  20  41]
  [ 41  19  41]
  ...
  [ 54  63  35]
  [ 53  62  34]
  [ 52  61  33]]

 [[ 37  21  42]
  [ 37  21  42]
  [ 42  20  42]
  ...
  [ 54  63  35]
  [ 53  62  34]
  [ 52  61  33]]]
[[[137 196 203]
  [138 197 204]
  [154 194 204]
  ...
  [211 220 229]
  [211 220 229]
  [211 220 229]]

 [[138 197 204]
  [138 197 204]
  [154 194 204]
  ...
  [212 221 230]
  [212 221 230]
  [212 221 230]]

 [[146 197 205]
  [146 197 205]
  [157 197 207]
  ...
  [208 220 231]
  [208 220 231]
  [208 220 231]]

 ...

 [[ 40  18  24]
  [ 45  23  29]
  [ 40  26  31]
  ..

In [5]:
#얼굴 탐지
def faceDetect(path, videoname, idnum):
    eye_detect = False
    face_cascade = cv2.CascadeClassifier('haarcascade_frontface.xml')
    eye_cascade = cv2.CascadeClassifier('haarcascade_eye.xml')
    info = ''
    count = 0
    
    try:
        video = cv2.VideoCapture(path)
    except:
        print('video loading failed.')
        return
    
    while True:
        ret, frame = video.read()
        if not ret:
            break
        if eye_detect:
            info = "Eye detection on"
        else:
            info = "Eye detection off"
        
        gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
        faces = face_cascade.detectMultiScale(gray, 1.3,5)
        #top, right, bottom, left = faces
        print(faces)
        #for (x,y,w,h) in faces:
        print("A face is located at pixel location Top: {}, Left: {}, Bottom: {}, Right: {}".format(top, left, bottom, right))

        #face_location 찾아서 파일로 저장
        face_image = Image.fromarray(frame[top:bottom, left:right])
        #Image.fromarray(face_image).show()
        face_image.save(videoname+'/'+idnum+'frame %d.jpg' %count)
        print('Saved frame%d.jpg' %count)
        count += 1
        
        

In [ ]:
#cascade 분류기를 사용한 얼굴인식

import cv2
import numpy as np
import face_recognition
import re
from matplotlib import pyplot as plt

dirname = 'deepfake-data_subset1/original_videos/'
videoname = '643049'
classnum = '_D_001'
video_path = dirname + videoname+'/'
frame_save_path = videoname+'/'+classnum+'_frame'
path = video_path+videoname+classnum+'.mp4'
#'C:\Users\user\Documents\cyber17\Face_Detection\'
video = cv2.VideoCapture(path)

videoframe = video.get(cv2.CAP_PROP_POS_FRAMES)
videocount = video.get(cv2.CAP_PROP_FRAME_COUNT)

createfolder(frame_save_path)

while video.isOpened():
    #ret 은 프레임이 존재하지 않을때 T/F 반환
    #frame 은 프레임 반환
    if(videoframe == videocount):
        video.open(path)
    
    faceDetect(path, videoname,classnum)


video.release()
cv2.destroyAllWindows()

## 여기는 얼굴 세부사항(눈, 코, 입, 귀 등) 표시용.

## 필요없다고 함~

In [ ]:

import face_alignment
from skimage import io
import os

videoname = 'sample1'
framepath = videoname+'_frame '

fa = face_alignment.FaceAlignment(face_alignment.LandmarksType._3D, flip_input=False)

count=0
for i in range(5): #len(os.walk(path).__next__()[2]
    print("start : ", i)
    input = io.imread(framepath+str(i)+'.jpg')
    preds = fa.get_landmarks(input)
    preds = Image.fromarray(preds)
    display(preds)
    #preds.save(videoname+'_frame_face/feature %d.jpg' %count)
    count += 1