OpenCV 사용


일단, 비디오를 불러와서 프레임단위로 추출 + 저장이 1차 목적

<참고>

https://docs.opencv.org/2.4/modules/highgui/doc/reading_and_writing_images_and_video.html 




* videoCapture 인터페이스를 이용한 베이직 코드


opencv_source_code/samples/python2/video.py




* basic 비디오 처리 샘플코드


opencv_source_code/samples/python2/video_dmtx.py




* 멀티쓰레드 비디오 처리 샘플코드


opencv_source_code/samples/python2/video_threaded.py

대기시간
k = cv2.waitKey(0)
if k == 27: #esc key
cv2.destroyAllWindows()
break

In [1]:
import os

def createfolder(folder):
    try:
        if not os.path.exists(folder):
            os.makedirs(folder)
    except OSError:
        print('Error: creating directory' + folder)


## path 경로 설정 해야해 미현아!!! 


In [2]:
import cv2

path = '/Users/hyeonjeong_baek/CyberProjects/Deep-t-ADIS/W8_ExtractFrame/sample3_frame'
video = cv2.VideoCapture('sample3.mp4')
count = 0

videoframe = video.get(cv2.CAP_PROP_POS_FRAMES)
videocount = video.get(cv2.CAP_PROP_FRAME_COUNT)

createfolder(path)

while video.isOpened():
    #ret 은 프레임이 존재하지 않을때 T/F 반환
    #frame 은 프레임 반환
    if(videoframe == videocount):
        video.open('sample3.mp4')
    
    ret, frame = video.read()
    if ret == False:
        print("Frame doesn't Exist")
        break
    
    try:
        cv2.imshow('sample3', frame)        
        cv2.imwrite('sample3_frame/frame %d.jpg' %count, frame)
        #print('Saved frame%d.jpg' %count)
        count += 1
        
    except :
        pass

video.release()
cv2.destroyAllWindows()


Frame doesn't Exist



**face_recognition 의 load_image_file 함수가 안먹어서 api 코드보고 바꿈**

In [3]:
import PIL
from PIL import Image

def load_image_file(file, mode='RGB'):
    im = PIL.Image.open(file)
    if mode:
        im = im.convert(mode)
    return np.array(im)

In [4]:
import os

directory = os.walk(path).__next__()[2]
print(len(directory))

337


## 샘플(연희얼굴 - frame 두 개만|)

In [12]:
import face_recognition

images = []
for i in range(2):
    image = load_image_file("sample3_frame/frame "+str(i)+".jpg")
    images.append(image)

face_locations = []
for img in images:
    print(img)
    face_location = face_recognition.face_locations(img, model='cnn')
    #face_locations = face_recognition.face_locations(image)
    face_locations.append(face_location)

    
print(face_locations)
print("I found {} face(s) in this photograph.".format(len(face_locations)))

for face_location in face_locations:
    print(face_location)
    # Print the location of each face in this image
    top, right, bottom, left = face_location[0]
    print("A face is located at pixel location Top: {}, Left: {}, Bottom: {}, Right: {}".format(top, left, bottom, right))

    # You can access the actual face itself like this:
    face_image = image[top:bottom, left:right]
    pil_image = Image.fromarray(face_image)
    pil_image.show()

[[[174 137 121]
  [174 137 121]
  [174 137 121]
  ...
  [175 143 128]
  [175 143 128]
  [174 142 127]]

 [[174 137 121]
  [174 137 121]
  [174 137 121]
  ...
  [176 144 129]
  [175 143 128]
  [174 142 127]]

 [[174 137 121]
  [174 137 121]
  [174 137 121]
  ...
  [176 144 129]
  [175 143 128]
  [173 141 126]]

 ...

 [[114  66  44]
  [113  66  46]
  [108  63  44]
  ...
  [187 188 218]
  [172 173 203]
  [158 159 189]]

 [[116  68  45]
  [115  69  46]
  [111  66  45]
  ...
  [190 191 221]
  [175 176 206]
  [162 163 193]]

 [[114  67  41]
  [113  67  43]
  [110  65  42]
  ...
  [192 193 223]
  [180 181 211]
  [168 169 199]]]


TypeError: face_locations() got an unexpected keyword argument 'model'

## face_recognition 라이브러리를 이용해서 face frame 추출

**지금은 video -> frame 이미지 저장 -> 이미지 불러와서 얼굴만 따오기** 

이거를 아예 video -> 얼굴 프레임 저장으로 간추릴 예정임

In [13]:
import numpy as np
import face_recognition


# Load the jpg file into a numpy array
#image = face_recognition.load_image_file("/sample2_frame/frame 0.jpg")

images = []
#for i in range(len(os.walk(path).__next__()[2])):
for i in range(100):
    image = load_image_file("sample3_frame/frame "+str(i)+".jpg")
    images.append(image)
    

# Find all the faces in the image using the default HOG-based model.
# This method is fairly accurate, but not as accurate as the CNN model and not GPU accelerated.
# See also: find_faces_in_picture_cnn.py
face_locations = []
for img in images:
    face_location = face_recognition.face_locations(img, model="cnn")
    
    '''여기 model="cnn" 하면 원래 된다는데 내 컴퓨터로는 안됨 ㅜㅜㅜㅜ'''
    
    
    #face_locations = face_recognition.face_locations(image)
    #print("I found {} face(s) in this photograph.".format(len(face_locations)))
    face_locations.append(face_location)
    
print(face_locations)

for face_location in face_locations:

    # Print the location of each face in this image
    top, right, bottom, left = face_location[0]
    print("A face is located at pixel location Top: {}, Left: {}, Bottom: {}, Right: {}".format(top, left, bottom, right))

    # You can access the actual face itself like this:
    face_image = image[top:bottom, left:right]
    pil_image = Image.fromarray(face_image)
    pil_image.show()

TypeError: face_locations() got an unexpected keyword argument 'model'

conda install cmake

conda install -c menpo dlib

conda install face_recognition


conda install pandas, pytorch, torchvision 등등

https://face-recognition.readthedocs.io/en/latest/_modules/face_recognition/api.html#load_image_file 