OpenCV 사용


일단, 비디오를 불러와서 프레임단위로 추출 + 저장이 1차 목적

<참고>

https://docs.opencv.org/2.4/modules/highgui/doc/reading_and_writing_images_and_video.html 




* videoCapture 인터페이스를 이용한 베이직 코드


opencv_source_code/samples/python2/video.py




* basic 비디오 처리 샘플코드


opencv_source_code/samples/python2/video_dmtx.py




* 멀티쓰레드 비디오 처리 샘플코드


opencv_source_code/samples/python2/video_threaded.py

대기시간
k = cv2.waitKey(0)
if k == 27: #esc key
cv2.destroyAllWindows()
break

In [1]:
import os

def createfolder(folder):
    try:
        if not os.path.exists(folder):
            os.makedirs(folder)
    except OSError:
        print('Error: creating directory' + folder)


In [2]:
import PIL
from PIL import Image

def load_image_file(file, mode='RGB'):
    im = PIL.Image.open(file)
    if mode:
        im = im.convert(mode)
    return np.array(im)

## path 경로 설정 해야해 미현아!!! 


import cv2

path = '/Users/hyeonjeong_baek/CyberProjects/Deep-t-ADIS/W8_ExtractFrame/sample3_frame'
video = cv2.VideoCapture('sample3.mp4')
count = 0

videoframe = video.get(cv2.CAP_PROP_POS_FRAMES)
videocount = video.get(cv2.CAP_PROP_FRAME_COUNT)

createfolder(path)

while video.isOpened():
    #ret 은 프레임이 존재하지 않을때 T/F 반환
    #frame 은 프레임 반환
    if(videoframe == videocount):
        video.open('sample3.mp4')
    
    ret, frame = video.read()
    if ret == False:
        print("Frame doesn't Exist")
        break
    
    try:
        cv2.imshow('sample3', frame)        
        cv2.imwrite('sample3_frame/frame %d.jpg' %count, frame)
        #print('Saved frame%d.jpg' %count)
        count += 1
        
    except :
        pass

video.release()
cv2.destroyAllWindows()



**face_recognition 의 load_image_file 함수가 안먹어서 api 코드보고 바꿈**

import os

directory = os.walk(path).__next__()[2]
print(len(directory))

## 샘플(연희얼굴 - frame 두 개만|)

import face_recognition

images = []
for i in range(2):
    image = load_image_file("sample3_frame/frame "+str(i)+".jpg")
    images.append(image)

face_locations = []
for img in images:
    print(img)
    face_location = face_recognition.face_locations(img)
    #face_locations = face_recognition.face_locations(image)
    face_locations.append(face_location)

    
print(face_locations)
print("I found {} face(s) in this photograph.".format(len(face_locations)))

for face_location in face_locations:
    print(face_location)
    #print("image", image)
    # Print the location of each face in this image
    top, right, bottom, left = face_location[0]
    print("A face is located at pixel location Top: {}, Left: {}, Bottom: {}, Right: {}".format(top, left, bottom, right))

    # You can access the actual face itself like this:
    face_image = image[top:bottom, left:right]
    pil_image = Image.fromarray(face_image)
    pil_image.show()

## face_recognition 라이브러리를 이용해서 face frame 추출

**지금은 video -> frame 이미지 저장 -> 이미지 불러와서 얼굴만 따오기** 

이거를 아예 video -> 얼굴 프레임 저장으로 간추릴 예정임

import numpy as np
import face_recognition


#image = face_recognition.load_image_file("/sample2_frame/frame 0.jpg")

images = []
#for i in range(len(os.walk(path).__next__()[2])):
for i in range(100):
    image = load_image_file("sample3_frame/frame "+str(i)+".jpg")
    images.append(image)
    

face_locations = []
for img in images:
    face_location = face_recognition.face_locations(img, model="cnn")
    
    '''여기 model="cnn" 하면 원래 된다는데 내 컴퓨터로는 안됨 ㅜㅜㅜㅜ'''
    
    
    #face_locations = face_recognition.face_locations(image)
    #print("I found {} face(s) in this photograph.".format(len(face_locations)))
    face_locations.append(face_location)
    
print(face_locations)

for face_location in face_locations:

    # Print the location of each face in this image
    top, right, bottom, left = face_location[0]
    print("A face is located at pixel location Top: {}, Left: {}, Bottom: {}, Right: {}".format(top, left, bottom, right))

    # You can access the actual face itself like this:
    face_image = image[top:bottom, left:right]
    pil_image = Image.fromarray(face_image)
    pil_image.show()

https://face-recognition.readthedocs.io/en/latest/_modules/face_recognition/api.html#load_image_file 

# step 1

## mp4 파일 -> face frame 으로 바로 저장

In [3]:
import cv2
import numpy as np
import face_recognition

videoname = 'sample3'
path = '/Users/hyeonjeong_baek/CyberProjects/Deep-t-ADIS/W8_ExtractFrame/'+videoname+'_frame'
video = cv2.VideoCapture(videoname+'.mp4')
count = 0
faces = []

videoframe = video.get(cv2.CAP_PROP_POS_FRAMES)
videocount = video.get(cv2.CAP_PROP_FRAME_COUNT)

createfolder(path)

while video.isOpened():
    #ret 은 프레임이 존재하지 않을때 T/F 반환
    #frame 은 프레임 반환
    if(videoframe == videocount):
        video.open(videoname+'.mp4')
    
    ret, frame = video.read()
    frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
    print(frame)
    if ret == False:
        print("Frame doesn't Exist")
        bre굴 detection 한 프레임으로 
        #face_location 은 얼굴 위치(행렬에서)
        face_location = face_recognition.face_locations(frame)
        top, right, bottom, left = face_location[0]
        print("A face is located at pixel location Top: {}, Left: {}, Bottom: {}, Right: {}".format(top, left, bottom, right))

        #face_location 찾아서 파일로 저장
        face_image = Image.fromarray(frame[top:bottom, left:right])
        #Image.fromarray(face_image).show()
        face_image.save(videoname+'_frame/frame %d.jpg' %count)
        #print('Saved frame%d.jpg' %count)
        count += 1
        
    except :
        pass

print(faces)
video.release()
cv2.destroyAllWindows()



[[[174 137 122]
  [174 137 122]
  [174 137 122]
  ...
  [175 143 127]
  [175 143 127]
  [175 143 127]]

 [[174 137 122]
  [174 137 122]
  [174 137 122]
  ...
  [176 144 128]
  [175 143 127]
  [174 142 126]]

 [[174 137 122]
  [174 137 122]
  [174 137 122]
  ...
  [176 144 128]
  [175 143 127]
  [174 142 126]]

 ...

 [[114  67  46]
  [113  66  45]
  [108  62  44]
  ...
  [189 190 220]
  [171 172 202]
  [158 159 189]]

 [[115  69  43]
  [115  69  43]
  [111  66  45]
  ...
  [190 191 221]
  [175 176 206]
  [162 163 193]]

 [[113  67  41]
  [114  68  42]
  [109  64  43]
  ...
  [192 193 223]
  [178 179 209]
  [169 170 200]]]
A face is located at pixel location Top: 384, Left: 776, Bottom: 705, Right: 1097
[[[174 137 122]
  [174 137 122]
  [176 139 124]
  ...
  [175 143 127]
  [175 143 127]
  [175 143 127]]

 [[174 137 122]
  [174 137 122]
  [174 137 122]
  ...
  [176 144 128]
  [175 143 127]
  [175 143 127]]

 [[174 137 122]
  [174 137 122]
  [174 137 122]
  ...
  [176 144 128]
  [175 143

A face is located at pixel location Top: 333, Left: 718, Bottom: 718, Right: 1103
[[[177 140 125]
  [177 140 125]
  [178 141 126]
  ...
  [177 145 129]
  [176 144 128]
  [175 143 127]]

 [[177 140 125]
  [177 140 125]
  [178 141 126]
  ...
  [177 145 129]
  [176 144 128]
  [175 143 127]]

 [[177 140 125]
  [177 140 125]
  [178 141 126]
  ...
  [176 144 128]
  [175 143 127]
  [173 141 125]]

 ...

 [[ 62  21   5]
  [ 63  22   6]
  [ 63  22   6]
  ...
  [190 191 221]
  [190 191 221]
  [190 191 221]]

 [[ 70  29  13]
  [ 71  30  14]
  [ 71  30  14]
  ...
  [191 192 222]
  [191 192 222]
  [191 192 222]]

 [[ 80  39  23]
  [ 81  40  24]
  [ 81  40  24]
  ...
  [183 184 214]
  [183 184 214]
  [183 184 214]]]
A face is located at pixel location Top: 333, Left: 718, Bottom: 718, Right: 1103
[[[179 140 126]
  [179 140 126]
  [179 140 126]
  ...
  [177 145 129]
  [176 144 128]
  [175 143 127]]

 [[179 140 126]
  [179 140 126]
  [179 140 126]
  ...
  [177 145 129]
  [176 144 128]
  [175 143 127]]

A face is located at pixel location Top: 384, Left: 740, Bottom: 705, Right: 1061
[[[180 142 125]
  [180 142 125]
  [180 142 125]
  ...
  [167 135 119]
  [167 135 119]
  [167 135 119]]

 [[181 143 126]
  [180 142 125]
  [180 142 125]
  ...
  [167 135 119]
  [167 135 119]
  [167 135 119]]

 [[181 143 126]
  [180 142 125]
  [180 142 125]
  ...
  [167 135 119]
  [166 134 118]
  [166 134 118]]

 ...

 [[ 81  40  24]
  [ 82  41  25]
  [ 82  41  25]
  ...
  [165 169 198]
  [165 169 198]
  [165 169 198]]

 [[ 90  49  33]
  [ 90  49  33]
  [ 89  48  32]
  ...
  [175 179 208]
  [175 179 208]
  [175 179 208]]

 [[ 98  57  41]
  [ 99  58  42]
  [ 97  56  40]
  ...
  [185 189 218]
  [183 187 216]
  [183 187 216]]]
A face is located at pixel location Top: 384, Left: 740, Bottom: 705, Right: 1061
[[[180 144 126]
  [179 143 125]
  [179 143 125]
  ...
  [168 136 120]
  [167 135 119]
  [167 135 119]]

 [[179 143 125]
  [179 143 125]
  [179 143 125]
  ...
  [167 135 119]
  [167 135 119]
  [167 135 119]]

A face is located at pixel location Top: 384, Left: 740, Bottom: 705, Right: 1061
[[[180 144 126]
  [179 143 125]
  [179 143 125]
  ...
  [170 139 120]
  [172 141 122]
  [172 141 122]]

 [[180 144 126]
  [180 144 126]
  [180 144 126]
  ...
  [170 139 120]
  [170 139 120]
  [170 139 120]]

 [[180 144 126]
  [180 144 126]
  [180 144 126]
  ...
  [169 138 119]
  [170 139 120]
  [170 139 120]]

 ...

 [[ 74  33  13]
  [ 74  33  13]
  [ 74  33  13]
  ...
  [178 180 207]
  [176 178 205]
  [174 176 203]]

 [[ 76  35  15]
  [ 76  35  15]
  [ 76  35  15]
  ...
  [185 187 214]
  [185 187 214]
  [181 183 210]]

 [[ 77  36  16]
  [ 77  36  16]
  [ 77  36  16]
  ...
  [182 184 211]
  [180 182 209]
  [180 182 209]]]
A face is located at pixel location Top: 384, Left: 740, Bottom: 705, Right: 1061
[[[180 144 126]
  [180 144 126]
  [180 144 126]
  ...
  [169 138 119]
  [170 139 120]
  [170 139 120]]

 [[180 144 126]
  [180 144 126]
  [180 144 126]
  ...
  [169 138 119]
  [169 138 119]
  [169 138 119]]

A face is located at pixel location Top: 384, Left: 740, Bottom: 705, Right: 1061
[[[181 145 127]
  [180 144 126]
  [180 144 126]
  ...
  [173 142 123]
  [173 142 123]
  [173 142 123]]

 [[181 145 127]
  [181 145 127]
  [180 144 126]
  ...
  [172 141 122]
  [172 141 122]
  [172 141 122]]

 [[181 145 127]
  [181 145 127]
  [180 144 126]
  ...
  [170 139 120]
  [170 139 120]
  [170 139 120]]

 ...

 [[ 74  33  15]
  [ 71  30  12]
  [ 70  29  11]
  ...
  [183 184 214]
  [184 185 215]
  [184 185 215]]

 [[ 73  32  14]
  [ 73  32  14]
  [ 71  30  12]
  ...
  [178 179 209]
  [185 186 216]
  [187 188 218]]

 [[ 71  30  12]
  [ 73  32  14]
  [ 73  32  14]
  ...
  [175 176 206]
  [180 181 211]
  [182 183 213]]]
A face is located at pixel location Top: 384, Left: 740, Bottom: 705, Right: 1061
[[[181 145 127]
  [181 145 127]
  [181 145 127]
  ...
  [173 142 123]
  [173 142 123]
  [173 142 123]]

 [[181 145 127]
  [181 145 127]
  [181 145 127]
  ...
  [172 141 122]
  [172 141 122]
  [172 141 122]]

A face is located at pixel location Top: 348, Left: 705, Bottom: 669, Right: 1026
[[[179 143 125]
  [179 143 125]
  [179 143 125]
  ...
  [170 139 120]
  [169 138 119]
  [168 137 118]]

 [[179 143 125]
  [179 143 125]
  [179 143 125]
  ...
  [169 138 119]
  [167 136 117]
  [166 135 116]]

 [[179 143 125]
  [179 143 125]
  [180 144 126]
  ...
  [165 134 115]
  [162 131 112]
  [162 131 112]]

 ...

 [[ 68  27  11]
  [ 70  29  13]
  [ 71  30  14]
  ...
  [180 181 211]
  [177 178 208]
  [183 184 214]]

 [[ 68  27  11]
  [ 70  29  13]
  [ 71  30  14]
  ...
  [185 186 216]
  [184 185 215]
  [190 191 221]]

 [[ 68  27  11]
  [ 70  29  13]
  [ 71  30  14]
  ...
  [187 188 218]
  [187 188 218]
  [192 193 223]]]
A face is located at pixel location Top: 348, Left: 705, Bottom: 669, Right: 1026
[[[180 144 126]
  [180 144 126]
  [180 144 126]
  ...
  [169 138 119]
  [167 136 117]
  [166 135 116]]

 [[180 144 126]
  [180 144 126]
  [180 144 126]
  ...
  [167 136 117]
  [165 134 115]
  [163 132 113]]

A face is located at pixel location Top: 348, Left: 740, Bottom: 669, Right: 1061
[[[180 144 126]
  [181 145 127]
  [183 147 129]
  ...
  [176 145 126]
  [174 143 124]
  [173 142 123]]

 [[181 145 127]
  [181 145 127]
  [181 145 127]
  ...
  [174 143 124]
  [174 143 124]
  [173 142 123]]

 [[183 147 129]
  [181 145 127]
  [180 144 126]
  ...
  [170 139 120]
  [169 138 119]
  [168 137 118]]

 ...

 [[ 44  18   6]
  [ 44  18   6]
  [ 44  18   6]
  ...
  [192 196 225]
  [188 192 221]
  [180 184 213]]

 [[ 46  20   8]
  [ 46  20   8]
  [ 46  20   8]
  ...
  [192 196 225]
  [190 194 223]
  [187 191 220]]

 [[ 49  23  11]
  [ 49  23  11]
  [ 49  23  11]
  ...
  [190 194 223]
  [190 194 223]
  [189 193 222]]]
A face is located at pixel location Top: 348, Left: 740, Bottom: 669, Right: 1061
[[[183 147 129]
  [183 147 129]
  [183 147 129]
  ...
  [174 143 124]
  [174 143 124]
  [174 143 124]]

 [[183 147 129]
  [183 147 129]
  [183 147 129]
  ...
  [174 143 124]
  [173 142 123]
  [173 142 123]]

A face is located at pixel location Top: 348, Left: 740, Bottom: 669, Right: 1061
[[[183 147 129]
  [181 145 127]
  [181 145 127]
  ...
  [175 141 123]
  [176 142 124]
  [177 143 125]]

 [[183 147 129]
  [181 145 127]
  [181 145 127]
  ...
  [176 142 124]
  [176 142 124]
  [176 142 124]]

 [[183 147 129]
  [181 145 127]
  [181 145 127]
  ...
  [176 142 124]
  [176 142 124]
  [176 142 124]]

 ...

 [[ 46  20   8]
  [ 46  20   8]
  [ 46  20   8]
  ...
  [197 198 228]
  [197 198 228]
  [197 198 228]]

 [[ 48  22  10]
  [ 48  22  10]
  [ 48  22  10]
  ...
  [197 198 228]
  [197 198 228]
  [197 198 228]]

 [[ 49  23  11]
  [ 49  23  11]
  [ 49  23  11]
  ...
  [195 196 226]
  [195 196 226]
  [195 196 226]]]
A face is located at pixel location Top: 348, Left: 740, Bottom: 669, Right: 1061
[[[181 145 127]
  [180 144 126]
  [180 144 126]
  ...
  [175 141 123]
  [176 142 124]
  [177 143 125]]

 [[181 145 127]
  [180 144 126]
  [180 144 126]
  ...
  [176 142 124]
  [176 142 124]
  [176 142 124]]

A face is located at pixel location Top: 384, Left: 705, Bottom: 705, Right: 1026
[[[181 145 127]
  [180 144 126]
  [180 144 126]
  ...
  [173 142 123]
  [173 142 123]
  [173 142 123]]

 [[181 145 127]
  [180 144 126]
  [180 144 126]
  ...
  [173 142 123]
  [173 142 123]
  [173 142 123]]

 [[180 144 126]
  [180 144 126]
  [180 144 126]
  ...
  [173 142 123]
  [173 142 123]
  [173 142 123]]

 ...

 [[ 46  20   6]
  [ 46  20   6]
  [ 44  18   4]
  ...
  [199 200 230]
  [199 200 230]
  [199 200 230]]

 [[ 48  22   8]
  [ 46  20   6]
  [ 44  18   4]
  ...
  [201 202 232]
  [201 202 232]
  [201 202 232]]

 [[ 48  22   8]
  [ 46  20   6]
  [ 44  18   4]
  ...
  [201 202 232]
  [201 202 232]
  [201 202 232]]]
A face is located at pixel location Top: 384, Left: 705, Bottom: 705, Right: 1026
[[[179 142 127]
  [179 142 127]
  [179 142 127]
  ...
  [173 142 123]
  [173 142 123]
  [173 142 123]]

 [[179 142 127]
  [179 142 127]
  [179 142 127]
  ...
  [173 142 123]
  [173 142 123]
  [173 142 123]]

A face is located at pixel location Top: 297, Left: 502, Bottom: 759, Right: 964
[[[183 142 126]
  [183 142 126]
  [183 142 126]
  ...
  [169 138 119]
  [169 138 119]
  [169 138 119]]

 [[182 141 125]
  [182 141 125]
  [182 141 125]
  ...
  [169 138 119]
  [169 138 119]
  [169 138 119]]

 [[181 140 124]
  [181 140 124]
  [181 140 124]
  ...
  [170 139 120]
  [169 138 119]
  [169 138 119]]

 ...

 [[242 143  63]
  [243 144  64]
  [243 144  64]
  ...
  [194 196 223]
  [192 194 221]
  [190 192 219]]

 [[242 143  63]
  [243 144  64]
  [243 144  64]
  ...
  [192 194 221]
  [191 193 220]
  [189 191 218]]

 [[242 143  63]
  [242 143  63]
  [243 144  64]
  ...
  [191 193 220]
  [190 192 219]
  [189 191 218]]]
A face is located at pixel location Top: 333, Left: 504, Bottom: 718, Right: 889
[[[184 143 127]
  [184 143 127]
  [183 142 126]
  ...
  [167 133 115]
  [167 133 115]
  [168 134 116]]

 [[184 143 127]
  [183 142 126]
  [183 142 126]
  ...
  [169 135 117]
  [169 135 117]
  [169 135 117]]



A face is located at pixel location Top: 246, Left: 451, Bottom: 708, Right: 913
[[[192 149 134]
  [192 149 134]
  [194 151 136]
  ...
  [175 141 123]
  [175 141 123]
  [175 141 123]]

 [[192 149 134]
  [192 149 134]
  [194 151 136]
  ...
  [175 141 123]
  [175 141 123]
  [175 141 123]]

 [[192 149 134]
  [194 151 136]
  [194 151 136]
  ...
  [175 141 123]
  [175 141 123]
  [175 141 123]]

 ...

 [[ 57  35  17]
  [ 57  35  17]
  [ 57  35  17]
  ...
  [198 233 214]
  [197 232 213]
  [197 232 213]]

 [[ 57  35  17]
  [ 57  35  17]
  [ 57  35  17]
  ...
  [198 233 214]
  [198 233 214]
  [198 233 214]]

 [[ 57  35  17]
  [ 57  35  17]
  [ 57  35  17]
  ...
  [198 233 214]
  [198 233 214]
  [198 233 214]]]
A face is located at pixel location Top: 246, Left: 451, Bottom: 708, Right: 913
[[[192 149 134]
  [192 149 134]
  [194 151 136]
  ...
  [175 141 123]
  [175 141 123]
  [175 141 123]]

 [[192 149 134]
  [194 151 136]
  [194 151 136]
  ...
  [175 141 123]
  [175 141 123]
  [175 141 123]]



A face is located at pixel location Top: 420, Left: 740, Bottom: 741, Right: 1061
[[[182 141 125]
  [182 141 125]
  [183 142 126]
  ...
  [154 129 112]
  [154 129 112]
  [154 129 112]]

 [[182 141 125]
  [182 141 125]
  [182 141 125]
  ...
  [154 129 112]
  [154 129 112]
  [154 129 112]]

 [[181 140 124]
  [181 140 124]
  [182 141 125]
  ...
  [154 129 112]
  [154 129 112]
  [154 129 112]]

 ...

 [[ 42  27  18]
  [ 42  27  18]
  [ 42  27  18]
  ...
  [187 210 237]
  [180 203 230]
  [176 199 226]]

 [[ 42  27  18]
  [ 42  27  18]
  [ 42  27  18]
  ...
  [188 213 239]
  [181 206 232]
  [176 201 227]]

 [[ 42  27  18]
  [ 42  27  18]
  [ 42  27  18]
  ...
  [190 215 241]
  [185 210 236]
  [181 206 232]]]
A face is located at pixel location Top: 439, Left: 795, Bottom: 706, Right: 1062
[[[180 139 123]
  [181 140 124]
  [181 140 124]
  ...
  [154 129 112]
  [154 129 112]
  [154 129 112]]

 [[181 140 124]
  [181 140 124]
  [181 140 124]
  ...
  [154 129 112]
  [154 129 112]
  [154 129 112]]

[[[164 128 110]
  [164 128 110]
  [164 128 110]
  ...
  [147 122 103]
  [147 122 103]
  [147 122 103]]

 [[164 128 110]
  [164 128 110]
  [164 128 110]
  ...
  [147 122 103]
  [147 122 103]
  [147 122 103]]

 [[164 128 110]
  [164 128 110]
  [164 128 110]
  ...
  [148 123 104]
  [148 123 104]
  [148 123 104]]

 ...

 [[ 59  46  39]
  [ 59  46  39]
  [ 55  42  35]
  ...
  [160 176 203]
  [159 175 202]
  [158 174 201]]

 [[ 54  41  34]
  [ 55  42  35]
  [ 53  40  33]
  ...
  [155 171 198]
  [155 171 198]
  [156 172 199]]

 [[ 47  34  27]
  [ 47  34  27]
  [ 48  35  28]
  ...
  [155 171 198]
  [155 171 198]
  [157 173 200]]]
[[[164 128 110]
  [164 128 110]
  [164 128 110]
  ...
  [147 122 103]
  [147 122 103]
  [147 122 103]]

 [[164 128 110]
  [164 128 110]
  [164 128 110]
  ...
  [147 122 103]
  [147 122 103]
  [147 122 103]]

 [[164 128 110]
  [164 128 110]
  [164 128 110]
  ...
  [148 123 104]
  [148 123 104]
  [148 123 104]]

 ...

 [[ 33  21  11]
  [ 32  20  10]
  [ 32  20  10]
  ..

[[[164 127 112]
  [163 126 111]
  [163 126 111]
  ...
  [127 102  85]
  [128 103  86]
  [131 106  89]]

 [[164 127 112]
  [163 126 111]
  [163 126 111]
  ...
  [124  99  82]
  [128 103  86]
  [129 104  87]]

 [[164 127 112]
  [163 126 111]
  [163 126 111]
  ...
  [124  99  82]
  [128 103  86]
  [129 104  87]]

 ...

 [[ 43  26  16]
  [ 43  26  16]
  [ 43  26  16]
  ...
  [153 165 187]
  [153 165 187]
  [153 165 187]]

 [[ 43  26  16]
  [ 43  26  16]
  [ 43  26  16]
  ...
  [155 167 189]
  [155 167 189]
  [155 167 189]]

 [[ 42  25  15]
  [ 42  25  15]
  [ 42  25  15]
  ...
  [161 173 195]
  [161 173 195]
  [161 173 195]]]
[[[164 127 112]
  [163 126 111]
  [163 126 111]
  ...
  [129 104  87]
  [130 105  88]
  [133 108  91]]

 [[164 127 112]
  [163 126 111]
  [163 126 111]
  ...
  [127 102  85]
  [129 104  87]
  [130 105  88]]

 [[164 127 112]
  [163 126 111]
  [163 126 111]
  ...
  [126 101  84]
  [128 103  86]
  [129 104  87]]

 ...

 [[ 36  19  11]
  [ 36  19  11]
  [ 36  19  11]
  ..

[[[157 122 109]
  [158 123 110]
  [158 123 110]
  ...
  [131 106  89]
  [131 106  89]
  [131 106  89]]

 [[158 123 110]
  [158 123 110]
  [160 125 112]
  ...
  [130 105  88]
  [130 105  88]
  [130 105  88]]

 [[158 123 110]
  [158 123 110]
  [160 125 112]
  ...
  [128 103  86]
  [128 103  86]
  [128 103  86]]

 ...

 [[ 35  19   6]
  [ 36  20   7]
  [ 37  21   8]
  ...
  [155 164 189]
  [155 164 189]
  [158 167 192]]

 [[ 35  19   6]
  [ 36  20   7]
  [ 37  21   8]
  ...
  [147 156 181]
  [150 159 184]
  [150 159 184]]

 [[ 36  20   7]
  [ 37  21   8]
  [ 38  22   9]
  ...
  [147 156 181]
  [149 158 183]
  [153 162 187]]]
[[[157 122 109]
  [157 122 109]
  [157 122 109]
  ...
  [131 106  89]
  [131 106  89]
  [131 106  89]]

 [[158 123 110]
  [157 122 109]
  [158 123 110]
  ...
  [129 104  87]
  [130 105  88]
  [130 105  88]]

 [[158 123 110]
  [158 123 110]
  [158 123 110]
  ...
  [128 103  86]
  [128 103  86]
  [128 103  86]]

 ...

 [[ 39  20   6]
  [ 39  20   6]
  [ 40  21   7]
  ..

[[[154 121 110]
  [154 121 110]
  [153 120 109]
  ...
  [134 109  92]
  [134 109  92]
  [134 109  92]]

 [[154 121 110]
  [153 120 109]
  [153 120 109]
  ...
  [134 109  92]
  [134 109  92]
  [134 109  92]]

 [[153 120 109]
  [153 120 109]
  [153 120 109]
  ...
  [136 111  94]
  [136 111  94]
  [136 111  94]]

 ...

 [[ 42  26  11]
  [ 42  26  11]
  [ 42  26  11]
  ...
  [162 171 194]
  [162 171 194]
  [162 171 194]]

 [[ 43  27  12]
  [ 43  27  12]
  [ 43  27  12]
  ...
  [160 169 192]
  [160 169 192]
  [160 169 192]]

 [[ 43  27  12]
  [ 43  27  12]
  [ 43  27  12]
  ...
  [157 166 189]
  [157 166 189]
  [158 167 190]]]
[[[153 120 109]
  [153 120 109]
  [153 120 109]
  ...
  [137 112  95]
  [138 113  96]
  [140 115  98]]

 [[153 120 109]
  [153 120 109]
  [153 120 109]
  ...
  [140 115  98]
  [141 116  99]
  [142 117 100]]

 [[153 120 109]
  [153 120 109]
  [153 120 109]
  ...
  [142 117 100]
  [143 118 101]
  [143 118 101]]

 ...

 [[ 41  20   7]
  [ 42  21   8]
  [ 42  21   8]
  ..

A face is located at pixel location Top: 663, Left: 811, Bottom: 885, Right: 1034
[[[157 131 119]
  [157 131 119]
  [158 132 120]
  ...
  [138 119 103]
  [138 119 103]
  [138 119 103]]

 [[157 131 119]
  [157 131 119]
  [158 132 120]
  ...
  [138 119 103]
  [138 119 103]
  [138 119 103]]

 [[158 132 120]
  [158 132 120]
  [158 132 120]
  ...
  [137 118 102]
  [137 118 102]
  [137 118 102]]

 ...

 [[208 128  58]
  [208 128  58]
  [208 128  58]
  ...
  [163 175 208]
  [163 175 208]
  [163 175 208]]

 [[208 128  58]
  [208 128  58]
  [209 129  59]
  ...
  [163 175 208]
  [165 177 210]
  [165 177 210]]

 [[208 128  58]
  [208 128  58]
  [209 129  59]
  ...
  [162 174 207]
  [163 175 208]
  [163 175 208]]]
A face is located at pixel location Top: 676, Left: 820, Bottom: 861, Right: 1005
[[[156 130 120]
  [157 131 121]
  [159 133 123]
  ...
  [138 119 105]
  [138 119 105]
  [138 119 105]]

 [[157 131 121]
  [158 132 122]
  [159 133 123]
  ...
  [137 118 104]
  [137 118 104]
  [138 119 105]]

A face is located at pixel location Top: 573, Left: 778, Bottom: 758, Right: 964
[[[116  97  83]
  [116  97  83]
  [116  97  83]
  ...
  [145 126 114]
  [146 127 115]
  [149 130 118]]

 [[117  98  84]
  [117  98  84]
  [117  98  84]
  ...
  [145 126 114]
  [146 127 115]
  [147 128 116]]

 [[119 100  86]
  [119 100  86]
  [119 100  86]
  ...
  [145 126 114]
  [146 127 115]
  [146 127 115]]

 ...

 [[175 108  40]
  [175 108  40]
  [175 108  40]
  ...
  [157 175 211]
  [157 175 211]
  [157 175 211]]

 [[173 106  38]
  [173 106  38]
  [173 106  38]
  ...
  [157 175 213]
  [157 175 213]
  [157 175 213]]

 [[173 106  38]
  [173 106  38]
  [173 106  38]
  ...
  [157 175 213]
  [157 175 213]
  [157 175 213]]]
[[[132 111  96]
  [132 111  96]
  [132 111  96]
  ...
  [138 119 107]
  [137 118 106]
  [137 118 106]]

 [[132 111  96]
  [132 111  96]
  [132 111  96]
  ...
  [138 119 107]
  [137 118 106]
  [137 118 106]]

 [[132 111  96]
  [132 111  96]
  [132 111  96]
  ...
  [137 118 106]
  [137 118 

A face is located at pixel location Top: 390, Left: 637, Bottom: 613, Right: 860
[[[ 94  84  72]
  [ 94  84  72]
  [ 94  84  72]
  ...
  [ 78  68  67]
  [ 78  68  67]
  [ 78  68  67]]

 [[ 94  84  72]
  [ 94  84  72]
  [ 94  84  72]
  ...
  [ 78  68  67]
  [ 78  68  67]
  [ 78  68  67]]

 [[ 95  85  73]
  [ 95  85  73]
  [ 95  85  73]
  ...
  [ 78  68  67]
  [ 78  68  67]
  [ 78  68  67]]

 ...

 [[184 109  39]
  [184 109  39]
  [184 109  39]
  ...
  [188 199 230]
  [188 199 230]
  [188 199 230]]

 [[176 101  31]
  [176 101  31]
  [176 101  31]
  ...
  [188 199 230]
  [188 199 230]
  [188 199 230]]

 [[171  96  26]
  [171  96  26]
  [171  96  26]
  ...
  [188 199 230]
  [188 199 230]
  [188 199 230]]]
A face is located at pixel location Top: 350, Left: 617, Bottom: 617, Right: 884
[[[ 98  88  76]
  [ 98  88  76]
  [ 97  87  75]
  ...
  [ 79  69  68]
  [ 79  69  68]
  [ 79  69  68]]

 [[ 98  88  76]
  [ 98  88  76]
  [ 98  88  76]
  ...
  [ 79  69  68]
  [ 79  69  68]
  [ 79  69  68]]



A face is located at pixel location Top: 241, Left: 740, Bottom: 562, Right: 1061
[[[105  88  80]
  [105  88  80]
  [105  88  80]
  ...
  [ 81  70  67]
  [ 81  70  67]
  [ 81  70  67]]

 [[105  88  80]
  [105  88  80]
  [105  88  80]
  ...
  [ 81  70  67]
  [ 81  70  67]
  [ 81  70  67]]

 [[105  88  80]
  [105  88  80]
  [105  88  80]
  ...
  [ 82  71  68]
  [ 81  70  67]
  [ 81  70  67]]

 ...

 [[ 50  27  14]
  [ 50  27  14]
  [ 48  25  12]
  ...
  [179 213 199]
  [178 212 198]
  [178 212 198]]

 [[ 49  26  13]
  [ 49  26  13]
  [ 48  25  12]
  ...
  [179 213 199]
  [178 212 198]
  [177 211 197]]

 [[ 48  25  12]
  [ 48  25  12]
  [ 47  24  11]
  ...
  [178 212 198]
  [177 211 197]
  [177 211 197]]]
A face is located at pixel location Top: 241, Left: 776, Bottom: 562, Right: 1097
[[[106  90  77]
  [106  90  77]
  [106  90  77]
  ...
  [ 80  69  64]
  [ 81  70  65]
  [ 81  70  65]]

 [[106  90  77]
  [106  90  77]
  [106  90  77]
  ...
  [ 81  70  65]
  [ 81  70  65]
  [ 81  70  65]]

A face is located at pixel location Top: 206, Left: 919, Bottom: 527, Right: 1240
[[[115  96  82]
  [115  96  82]
  [115  96  82]
  ...
  [163 135 122]
  [163 135 122]
  [163 135 122]]

 [[115  96  82]
  [115  96  82]
  [115  96  82]
  ...
  [163 135 122]
  [163 135 122]
  [163 135 122]]

 [[115  96  82]
  [115  96  82]
  [115  96  82]
  ...
  [163 135 122]
  [163 135 122]
  [163 135 122]]

 ...

 [[ 50  28  10]
  [ 50  28  10]
  [ 50  28  10]
  ...
  [187 219 199]
  [187 219 199]
  [187 219 199]]

 [[ 50  28  10]
  [ 50  28  10]
  [ 50  28  10]
  ...
  [186 218 198]
  [186 218 198]
  [186 218 198]]

 [[ 50  28  10]
  [ 50  28  10]
  [ 50  28  10]
  ...
  [187 219 199]
  [187 219 199]
  [187 219 199]]]
A face is located at pixel location Top: 241, Left: 919, Bottom: 562, Right: 1240
[[[133 107  95]
  [133 107  95]
  [133 107  95]
  ...
  [164 136 125]
  [164 136 125]
  [164 136 125]]

 [[133 107  95]
  [133 107  95]
  [133 107  95]
  ...
  [164 136 125]
  [164 136 125]
  [164 136 125]]

[[[160 137 122]
  [160 137 122]
  [160 137 122]
  ...
  [160 132 119]
  [160 132 119]
  [160 132 119]]

 [[160 137 122]
  [160 137 122]
  [160 137 122]
  ...
  [160 132 119]
  [160 132 119]
  [160 132 119]]

 [[160 137 122]
  [160 137 122]
  [160 137 122]
  ...
  [160 132 119]
  [160 132 119]
  [160 132 119]]

 ...

 [[ 38  17   2]
  [ 35  14   0]
  [ 34  13   0]
  ...
  [ 74  82  98]
  [ 73  81  97]
  [ 73  81  97]]

 [[ 39  18   3]
  [ 37  16   1]
  [ 35  14   0]
  ...
  [ 74  82  98]
  [ 74  82  98]
  [ 73  81  97]]

 [[ 40  19   4]
  [ 39  18   3]
  [ 37  16   1]
  ...
  [ 74  82  98]
  [ 74  82  98]
  [ 74  82  98]]]
[[[160 137 122]
  [160 137 122]
  [160 137 122]
  ...
  [156 128 115]
  [156 128 115]
  [156 128 115]]

 [[160 137 122]
  [160 137 122]
  [160 137 122]
  ...
  [156 128 115]
  [156 128 115]
  [156 128 115]]

 [[160 137 122]
  [160 137 122]
  [160 137 122]
  ...
  [156 128 115]
  [156 128 115]
  [156 128 115]]

 ...

 [[ 40  19   4]
  [ 40  19   4]
  [ 39  18   3]
  ..

[[[170 144 130]
  [170 144 130]
  [170 144 130]
  ...
  [174 151 136]
  [174 151 136]
  [174 151 136]]

 [[170 144 130]
  [170 144 130]
  [170 144 130]
  ...
  [174 151 136]
  [174 151 136]
  [174 151 136]]

 [[170 144 130]
  [170 144 130]
  [170 144 130]
  ...
  [174 151 136]
  [174 151 136]
  [174 151 136]]

 ...

 [[ 48  27  12]
  [ 48  27  12]
  [ 47  26  11]
  ...
  [183 212 200]
  [183 212 200]
  [183 212 200]]

 [[ 48  27  12]
  [ 48  27  12]
  [ 47  26  11]
  ...
  [183 212 200]
  [183 212 200]
  [183 212 200]]

 [[ 48  27  12]
  [ 48  27  12]
  [ 47  26  11]
  ...
  [183 212 200]
  [183 212 200]
  [183 212 200]]]
[[[172 144 131]
  [172 144 131]
  [171 143 130]
  ...
  [176 150 136]
  [175 149 135]
  [175 149 135]]

 [[172 144 131]
  [172 144 131]
  [171 143 130]
  ...
  [176 150 136]
  [176 150 136]
  [176 150 136]]

 [[172 144 131]
  [172 144 131]
  [172 144 131]
  ...
  [176 150 136]
  [176 150 136]
  [176 150 136]]

 ...

 [[ 49  28  13]
  [ 49  28  13]
  [ 48  27  12]
  ..

[[[138 118 100]
  [138 118 100]
  [137 117  99]
  ...
  [107  95  95]
  [107  95  95]
  [107  95  95]]

 [[138 118 100]
  [138 118 100]
  [137 117  99]
  ...
  [107  95  95]
  [107  95  95]
  [107  95  95]]

 [[138 118 100]
  [138 118 100]
  [137 117  99]
  ...
  [107  95  95]
  [107  95  95]
  [107  95  95]]

 ...

 [[135  83  51]
  [135  83  51]
  [135  83  51]
  ...
  [199 242 223]
  [199 242 223]
  [199 242 223]]

 [[132  80  48]
  [132  80  48]
  [132  80  48]
  ...
  [199 242 223]
  [199 242 223]
  [199 242 223]]

 [[130  78  46]
  [130  78  46]
  [130  78  46]
  ...
  [198 241 222]
  [198 241 222]
  [198 241 222]]]
[[[139 119 101]
  [139 119 101]
  [139 119 101]
  ...
  [105  93  95]
  [107  95  97]
  [107  95  97]]

 [[139 119 101]
  [139 119 101]
  [139 119 101]
  ...
  [107  95  97]
  [107  95  97]
  [107  95  97]]

 [[139 119 101]
  [139 119 101]
  [139 119 101]
  ...
  [108  96  98]
  [108  96  98]
  [108  96  98]]

 ...

 [[123  63  40]
  [123  63  40]
  [123  63  40]
  ..

[[[126 123 108]
  [126 123 108]
  [126 123 108]
  ...
  [113 101  91]
  [113 101  91]
  [113 101  91]]

 [[125 122 107]
  [125 122 107]
  [125 122 107]
  ...
  [113 101  91]
  [113 101  91]
  [113 101  91]]

 [[125 122 107]
  [125 122 107]
  [125 122 107]
  ...
  [113 101  91]
  [113 101  91]
  [113 101  91]]

 ...

 [[123  65  28]
  [122  64  27]
  [120  62  25]
  ...
  [167 217 205]
  [167 217 205]
  [167 217 205]]

 [[123  65  28]
  [122  64  27]
  [120  62  25]
  ...
  [169 219 207]
  [169 219 207]
  [169 219 207]]

 [[124  66  29]
  [123  65  28]
  [122  64  27]
  ...
  [169 219 207]
  [169 219 207]
  [169 219 207]]]
[[[124 121 108]
  [124 121 108]
  [124 121 108]
  ...
  [159 147 137]
  [159 147 137]
  [160 148 138]]

 [[122 119 106]
  [122 119 106]
  [122 119 106]
  ...
  [159 147 137]
  [159 147 137]
  [159 147 137]]

 [[122 119 106]
  [122 119 106]
  [122 119 106]
  ...
  [159 147 137]
  [159 147 137]
  [159 147 137]]

 ...

 [[119  63  25]
  [119  63  25]
  [119  63  25]
  ..

A face is located at pixel location Top: 231, Left: 854, Bottom: 498, Right: 1122
[[[108  91  81]
  [108  91  81]
  [107  90  80]
  ...
  [160 146 132]
  [161 147 133]
  [161 147 133]]

 [[108  91  81]
  [108  91  81]
  [107  90  80]
  ...
  [160 146 132]
  [160 146 132]
  [160 146 132]]

 [[108  91  81]
  [108  91  81]
  [107  90  80]
  ...
  [160 146 132]
  [160 146 132]
  [160 146 132]]

 ...

 [[162 112  79]
  [164 114  81]
  [164 114  81]
  ...
  [169 218 209]
  [169 218 209]
  [169 218 209]]

 [[162 112  79]
  [164 114  81]
  [163 113  80]
  ...
  [169 218 209]
  [169 218 209]
  [169 218 209]]

 [[162 112  79]
  [163 113  80]
  [163 113  80]
  ...
  [169 218 209]
  [169 218 209]
  [169 218 209]]]
A face is located at pixel location Top: 266, Left: 935, Bottom: 489, Right: 1157
[[[107  90  80]
  [107  90  80]
  [106  89  79]
  ...
  [165 151 137]
  [167 153 139]
  [167 153 139]]

 [[107  90  80]
  [107  90  80]
  [106  89  79]
  ...
  [167 153 139]
  [167 153 139]
  [165 151 137]]

A face is located at pixel location Top: 379, Left: 1062, Bottom: 647, Right: 1330
[[[152 126 105]
  [152 126 105]
  [152 126 105]
  ...
  [165 149 132]
  [164 148 131]
  [164 148 131]]

 [[152 126 105]
  [152 126 105]
  [152 126 105]
  ...
  [164 148 131]
  [164 148 131]
  [164 148 131]]

 [[152 126 105]
  [152 126 105]
  [152 126 105]
  ...
  [164 148 131]
  [164 148 131]
  [163 147 130]]

 ...

 [[206 138  48]
  [210 142  52]
  [214 146  56]
  ...
  [175 222 211]
  [175 222 211]
  [175 222 211]]

 [[218 153  46]
  [222 157  50]
  [225 160  53]
  ...
  [176 223 212]
  [175 222 211]
  [175 222 211]]

 [[225 160  53]
  [229 164  57]
  [232 167  60]
  ...
  [176 223 212]
  [175 222 211]
  [175 222 211]]]
[[[151 124 106]
  [151 124 106]
  [151 124 106]
  ...
  [164 148 131]
  [164 148 131]
  [164 148 131]]

 [[152 125 107]
  [152 125 107]
  [152 125 107]
  ...
  [163 147 130]
  [163 147 130]
  [163 147 130]]

 [[152 125 107]
  [152 125 107]
  [152 125 107]
  ...
  [162 146 129]
  [162 14

error: OpenCV(4.2.0) /Users/travis/build/skvark/opencv-python/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'


# step 2


## 얼굴 feature 추출 -> 2D facial landmark 표시하기

https://github.com/1adrianb/face-alignment

In [9]:
import face_alignment
from skimage import io
import os

framepath = videoname+'_frame/frame '

fa = face_alignment.FaceAlignment(face_alignment.LandmarksType._3D, flip_input=False)

for i in range(len(os.walk(path).__next__()[2])):
    input = io.imread(framepath+str(i)+'.jpg')
    preds = fa.get_landmarks(input)

AssertionError: Torch not compiled with CUDA enabled

conda 로 할 때 이것저것 



conda install cmake

conda install -c menpo dlib

conda install face_recognition


conda install pandas, pytorch, torchvision 등등